/**
 * core/servers/identity/ObjectRepository.js
 *
 * Envelope storage and delta log for signed Lively identity objects.
 *
 * Each object (world, part, file, settings, home manifest) is stored as a
 * sequence of signed envelope versions. The version chain is a DAG via
 * the prevCid field — analogous to Wave's DeltaStore.
 *
 * Schema (Postgres, via DATABASE_URL — see ../support/postgres-client.js):
 *
 *   objects table — one row per envelope version:
 *     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 *     obj_id      TEXT NOT NULL      — stable ObjID (12-char base64url)
 *     did         TEXT NOT NULL      — author's DID
 *     cid         TEXT NOT NULL      — content hash of this version
 *     prev_cid    TEXT               — NULL for genesis version
 *     type        TEXT NOT NULL      — world|part|file|settings|home|profile
 *     visibility  TEXT NOT NULL      — public|private|shared
 *     envelope    JSONB NOT NULL     — full envelope
 *     created_at  TEXT NOT NULL      — ISO 8601
 *
 *   CREATE UNIQUE INDEX idx_obj_cid ON objects(obj_id, cid)
 *   CREATE INDEX idx_obj_id ON objects(obj_id)
 *   CREATE INDEX idx_did ON objects(did)
 *   CREATE INDEX idx_objects_state_tags_gin ON objects USING GIN ((envelope #> '{state,tags}'))
 *
 *   "GENERATED BY DEFAULT AS IDENTITY" (not ALWAYS) deliberately: it lets a
 *   data migration insert explicit legacy id values with a plain INSERT
 *   (no OVERRIDING SYSTEM VALUE needed on every row) while every real put()
 *   insert still gets an auto-generated id as normal.
 *
 *   blob_refs table — which file or folder envelope a BlobStore cid
 *   currently belongs to (Encryption.md §5.3/§15.3), so the blob GET route
 *   can find the gating envelope without being able to decrypt it. Reflects
 *   only the latest version's membership (rewritten on every put(), not
 *   accumulated) — see _syncBlobRefsTx:
 *     blob_cid TEXT NOT NULL
 *     obj_id   TEXT NOT NULL
 *     PRIMARY KEY (blob_cid, obj_id)
 *
 *   postcard_reactions table — one reaction per (obj_id, did), replacing on
 *   re-react (PostcardDesignSpec-v2.md §5.1). Lives outside the envelope so
 *   it can still be written on an immutable, already-sent postcard:
 *     obj_id     TEXT NOT NULL
 *     did        TEXT NOT NULL
 *     emoji      TEXT NOT NULL
 *     created_at TEXT NOT NULL
 *     PRIMARY KEY (obj_id, did)
 *
 *   postcard_mailbox_hidden table — a per-viewer hide (PostcardDesignSpec-v2.md
 *   §6.3, "Layer 1"), independent of the envelope entirely:
 *     did       TEXT NOT NULL
 *     obj_id    TEXT NOT NULL
 *     hidden_at TEXT NOT NULL
 *     PRIMARY KEY (did, obj_id)
 *
 *   part_aliases table — human-readable name -> current objId, per author
 *   (Roadmap.md §3, "Phase 2 — Parts Name Aliasing"). One name per (did,
 *   alias_name); republishing a part under the same name repoints it. Kept
 *   up to date by put() itself (see below) rather than a separate write
 *   path, so nothing client-side needs to know this table exists:
 *     did         TEXT NOT NULL
 *     alias_name  TEXT NOT NULL
 *     obj_id      TEXT NOT NULL
 *     updated_at  TEXT NOT NULL
 *     PRIMARY KEY (did, alias_name)
 *
 * The latest version of an object is the row with the highest id for a
 * given obj_id. No DELETE ever happens on `objects` — that log is
 * append-only (postcard_reactions rows are deleted freely on un-react).
 *
 * Concurrency: put()/addRecipient() each acquire a Postgres advisory
 * transaction lock keyed on the target objId (pg_advisory_xact_lock) before
 * doing their read-then-decide-then-write sequence, and hold it for the
 * whole transaction. This replaces a correctness guarantee SQLite's
 * single-writer model used to provide by accident — under real concurrent
 * Postgres writers (the whole point of this migration), a bare row lock
 * (SELECT ... FOR UPDATE) wouldn't be enough on its own, since one real race
 * is two concurrent put()s for a brand-new objId with no row to lock yet.
 * An advisory lock keyed on the logical objId (not any particular row)
 * covers that case too, while leaving unrelated objIds fully concurrent.
 */

'use strict';

var path = require('path');
var postgresClient = require('../support/postgres-client');

var DDL =
  'CREATE TABLE IF NOT EXISTS objects (' +
  '  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,' +
  '  obj_id     TEXT NOT NULL,' +
  '  did        TEXT NOT NULL,' +
  '  cid        TEXT NOT NULL,' +
  '  prev_cid   TEXT,' +
  '  type       TEXT NOT NULL,' +
  '  visibility TEXT NOT NULL,' +
  '  envelope   JSONB NOT NULL,' +
  '  created_at TEXT NOT NULL' +
  ');\n' +
  'CREATE UNIQUE INDEX IF NOT EXISTS idx_obj_cid ON objects(obj_id, cid);\n' +
  'CREATE INDEX IF NOT EXISTS idx_obj_id ON objects(obj_id);\n' +
  'CREATE INDEX IF NOT EXISTS idx_did ON objects(did);\n' +
  // Supports listPublicParts' tag-membership filter (the `?` containment
  // operator) and listPublicPartTags' aggregation.
  'CREATE INDEX IF NOT EXISTS idx_objects_state_tags_gin ON objects USING GIN ((envelope #> \'{state,tags}\'));\n' +
  'CREATE TABLE IF NOT EXISTS blob_refs (' +
  '  blob_cid TEXT NOT NULL,' +
  '  obj_id   TEXT NOT NULL,' +
  '  PRIMARY KEY (blob_cid, obj_id)' +
  ');\n' +
  'CREATE TABLE IF NOT EXISTS postcard_reactions (' +
  '  obj_id     TEXT NOT NULL,' +
  '  did        TEXT NOT NULL,' +
  '  emoji      TEXT NOT NULL,' +
  '  created_at TEXT NOT NULL,' +
  '  PRIMARY KEY (obj_id, did)' +
  ');\n' +
  'CREATE TABLE IF NOT EXISTS postcard_mailbox_hidden (' +
  '  did       TEXT NOT NULL,' +
  '  obj_id    TEXT NOT NULL,' +
  '  hidden_at TEXT NOT NULL,' +
  '  PRIMARY KEY (did, obj_id)' +
  ');\n' +
  'CREATE TABLE IF NOT EXISTS part_aliases (' +
  '  did        TEXT NOT NULL,' +
  '  alias_name TEXT NOT NULL,' +
  '  obj_id     TEXT NOT NULL,' +
  '  updated_at TEXT NOT NULL,' +
  '  PRIMARY KEY (did, alias_name)' +
  ');';

var _bootstrapped = false;

// Returns the shared pg.Pool, bootstrapping the schema exactly once per
// process first. Nothing outside this file calls withDB() directly today
// (confirmed via grep) -- its contract changing from "a sqlite3.Database"
// to "a pg.Pool" is safe.
function withDB(thenDo) {
  var pool = postgresClient.getPool();
  if (_bootstrapped) return thenDo(null, pool);
  // Sent as one multi-statement string -- Postgres's simple query protocol
  // (used automatically by pool.query() when no parameters are given) runs
  // a semicolon-separated batch on one connection in order, giving the same
  // ordering guarantee sqlite3's db.serialize(...) gave, no library needed.
  pool.query(DDL, function (err) {
    if (err) return thenDo(err);
    _bootstrapped = true;
    thenDo(null, pool);
  });
}

// Shared by every function that needs to roll back a failed statement
// inside a transaction and release its client back to the pool before
// reporting the error to the caller.
function _rollbackAndRelease(client, release, err, thenDo) {
  client.query('ROLLBACK', function () {
    release();
    thenDo(err);
  });
}

// Acquires a per-objId advisory lock, scoped to the transaction (releases
// automatically on COMMIT/ROLLBACK or a dropped connection -- nothing to
// remember to unlock). Re-entrant per session, so it's safe even if a
// caller that already holds it calls into another function that acquires
// it again on the same client.
function _lockObjIdTx(client, objId, thenDo) {
  client.query('SELECT pg_advisory_xact_lock(hashtextextended($1, 0))', ['objects.put:' + objId], function (err) {
    thenDo(err);
  });
}

// Low-level "get latest envelope" that runs on a caller-supplied client --
// used inside put()/addRecipient()'s own transactions so the read and the
// decision it feeds are part of the same lock-held transaction as the
// eventual write. The public get() below is the plain pool-based version
// for ordinary reads that don't need that.
function _getLatestTx(client, objId, thenDo) {
  client.query(
    'SELECT envelope FROM objects WHERE obj_id = $1 ORDER BY id DESC LIMIT 1',
    [objId],
    function (err, result) {
      if (err) return thenDo(err);
      var row = result.rows[0];
      thenDo(null, row ? row.envelope : null);
    }
  );
}

// Overwrite the stored envelope+visibility for an existing (obj_id, cid)
// row in place, on a caller-supplied transaction client. Used when metadata
// (visibility / state / record.recipients) changes without the payload
// changing — cid only covers record.payload (see SignedSerializer.js /
// Crypto.computeCid), so such changes can never be represented as a new
// content-addressed version.
// Calls thenDo(err, envelope).
function _updateInPlaceTx(client, envelope, thenDo) {
  client.query(
    'UPDATE objects SET envelope = $1, visibility = $2 WHERE obj_id = $3 AND cid = $4',
    [envelope, envelope.visibility || 'public', envelope.objId, envelope.record.cid],
    function (err) {
      if (err) return thenDo(err);
      thenDo(null, envelope);
    }
  );
}

// Append a new envelope version for an object, or — if the incoming cid
// matches the latest stored version's cid (i.e. the payload is unchanged)
// but visibility/state/recipients differ — apply that metadata change in
// place instead of silently dropping it. A same-cid INSERT would otherwise
// collide with idx_obj_cid and be swallowed by put()'s old duplicate
// handling, which is exactly how visibility changes used to go missing.
// envelope must be a parsed JS object with at minimum:
//   { objId, did, type, visibility, record: { cid, prevCid } }
// Calls thenDo(err, { id, objId, cid, duplicate, changed }) where
// changed is 'content' | 'metadata' | 'none'.
//
// A genuinely new (non-metadata-only) version must chain off the current
// tip: envelope.record.prevCid must equal the existing latest version's cid,
// or be null iff no version exists yet. thenDo is called with an Error
// carrying { isConflict: true, currentCid } on violation (postcard_audit.md
// F20) — callers should surface this as a 409, not a 500, so a client can
// reload the current version and retry rather than assume server failure.
function put(envelope, thenDo) {
  if (!envelope || !envelope.objId || !envelope.record || !envelope.record.cid) {
    return thenDo(new Error('ObjectRepository.put: invalid envelope — missing objId or record.cid'));
  }

  // Keep part_aliases in sync with every successful put() of a named part,
  // regardless of which path below handled it (new version, in-place
  // metadata update, or true no-op duplicate) — upserting is idempotent, so
  // it's simplest and safest to always run it here rather than duplicate
  // this at each call site. A failure here logs but never fails the put()
  // itself; the alias is a resolution convenience, not the object record.
  // Runs after the main transaction below has committed (a separate, best-
  // effort side effect, same as before this migration).
  var callerThenDo = thenDo;
  thenDo = function (err, result) {
    if (err || envelope.type !== 'part' || !envelope.state || !envelope.state.partName) {
      return callerThenDo(err, result);
    }
    upsertPartAlias(envelope.did, envelope.state.partName, envelope.objId, function (aliasErr) {
      if (aliasErr) console.warn('[ObjectRepository] Failed to upsert part_aliases for', envelope.objId, ':', aliasErr.message);
      callerThenDo(err, result);
    });
  };

  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.connect(function (err, client, release) {
      if (err) return thenDo(err);
      client.query('BEGIN', function (err) {
        if (err) { release(); return thenDo(err); }

        _lockObjIdTx(client, envelope.objId, function (err) {
          if (err) return _rollbackAndRelease(client, release, err, thenDo);

          _getLatestTx(client, envelope.objId, function (err, existing) {
            if (err) return _rollbackAndRelease(client, release, err, thenDo);

            if (existing && existing.record.cid === envelope.record.cid) {
              var metadataChanged =
                existing.visibility !== envelope.visibility ||
                existing.constellation !== envelope.constellation ||
                JSON.stringify(existing.state || {}) !== JSON.stringify(envelope.state || {}) ||
                JSON.stringify(existing.record.recipients || []) !== JSON.stringify(envelope.record.recipients || []);

              if (!metadataChanged) {
                return client.query('COMMIT', function (err) {
                  release();
                  if (err) return thenDo(err);
                  thenDo(null, { objId: envelope.objId, cid: envelope.record.cid, duplicate: true, changed: 'none' });
                });
              }

              return _updateInPlaceTx(client, envelope, function (err) {
                if (err) return _rollbackAndRelease(client, release, err, thenDo);
                client.query('COMMIT', function (err) {
                  release();
                  if (err) return thenDo(err);
                  thenDo(null, { objId: envelope.objId, cid: envelope.record.cid, duplicate: true, changed: 'metadata' });
                });
              });
            }

            // prevCid chain-continuity check (postcard_audit.md F20): this is
            // reached only for a genuinely new content version (the same-cid
            // metadata-update path above already returned). The incoming
            // envelope must chain directly off whatever this transaction's
            // own locked read just saw as the current tip — or off nothing
            // (null) when no version exists yet. Runs inside the same
            // pg_advisory_xact_lock-held transaction as the read that
            // produced `existing`, so this is race-free under real
            // concurrent writers, not just a check-then-write on a stale read.
            // Without this, two editors both starting from the same base
            // version could both succeed, the second silently discarding the
            // first's content with no signal to either client.
            var incomingPrevCid = envelope.record.prevCid || null;
            var currentTipCid = existing ? existing.record.cid : null;
            if (incomingPrevCid !== currentTipCid) {
              var conflictErr = new Error(
                existing
                  ? 'prevCid mismatch: envelope chains off ' + incomingPrevCid +
                    ' but the current version of ' + envelope.objId + ' is ' + currentTipCid
                  : 'prevCid mismatch: envelope chains off ' + incomingPrevCid +
                    ' but no version of ' + envelope.objId + ' exists yet'
              );
              conflictErr.isConflict = true;
              conflictErr.currentCid = currentTipCid;
              return _rollbackAndRelease(client, release, conflictErr, thenDo);
            }

            var now = new Date().toISOString();
            client.query(
              'INSERT INTO objects (obj_id, did, cid, prev_cid, type, visibility, envelope, created_at)' +
              ' VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id',
              [
                envelope.objId,
                envelope.did,
                envelope.record.cid,
                envelope.record.prevCid || null,
                envelope.type || 'world',
                envelope.visibility || 'public',
                envelope,
                now
              ],
              function (err, result) {
                if (err) {
                  // UNIQUE constraint on (obj_id, cid) — the advisory lock
                  // above already serializes every writer for this objId,
                  // so this is now a defensive backstop (e.g. a stale
                  // retried request resubmitting an already-stored cid)
                  // rather than the primary defense it was under SQLite.
                  if (err.code === '23505') {
                    return client.query('ROLLBACK', function () {
                      release();
                      thenDo(null, { objId: envelope.objId, cid: envelope.record.cid, duplicate: true, changed: 'none' });
                    });
                  }
                  return _rollbackAndRelease(client, release, err, thenDo);
                }
                var newId = result.rows[0].id;
                _syncBlobRefsTx(client, envelope, function () {
                  client.query('COMMIT', function (err) {
                    release();
                    if (err) return thenDo(err);
                    thenDo(null, { id: newId, objId: envelope.objId, cid: envelope.record.cid, changed: 'content' });
                  });
                });
              }
            );
          });
        });
      });
    });
  });
}

// File envelopes carry a top-level (plaintext, server-consumed) `blobCid`
// field, and folder envelopes (Encryption.md §15) a top-level `blobCids`
// array — for private content the server can't read these out of the
// ciphertext payload, so the client duplicates them outside `record` (the
// encrypted copy inside the payload is the one the client trusts; see
// Encryption.md §5.3/§15.3). Indexed in blob_refs so the blob GET route can
// find the gating envelope. Errors are logged, not fatal — worst case a blob
// lookup 404s and the client retries the envelope PUT.
//
// Unlike a file envelope (whose blobCid never changes across its objId's
// lifetime — every upload gets a fresh objId, there is no "edit in place"),
// a folder envelope's member list, and therefore its blobCids, DOES change
// version to version (files added/removed). blob_refs has no cid column —
// it's a current-membership index, not a version history — so this clears
// every existing row for this obj_id before re-inserting the current set,
// rather than only ever adding (INSERT-only would leave a stale row for a
// file just removed from a folder, letting its blob stay fetchable via the
// folder's gating envelope forever — a real access-control gap, not just
// clutter). For a file envelope this is a harmless delete-then-reinsert of
// the same single row. Runs on the same transaction client put() holds its
// advisory lock and INSERT on, so the version row and its blob_refs are
// atomic together.
function _syncBlobRefsTx(client, envelope, thenDo) {
  var cids = [];
  if (envelope.type === 'file' && envelope.blobCid) cids = [envelope.blobCid];
  else if (envelope.type === 'folder' && Array.isArray(envelope.blobCids)) cids = envelope.blobCids;

  client.query('DELETE FROM blob_refs WHERE obj_id = $1', [envelope.objId], function (delErr) {
    if (delErr) console.warn('[ObjectRepository] Failed to clear stale blob_refs for', envelope.objId, ':', delErr.message);
    if (!cids.length) return thenDo();
    var remaining = cids.length;
    var done = false;
    cids.forEach(function (cid) {
      client.query(
        'INSERT INTO blob_refs (blob_cid, obj_id) VALUES ($1, $2) ON CONFLICT (blob_cid, obj_id) DO NOTHING',
        [cid, envelope.objId],
        function (err) {
          if (err) console.warn('[ObjectRepository] Failed to index blob_refs for', envelope.objId, ':', err.message);
          if (--remaining === 0 && !done) { done = true; thenDo(); }
        }
      );
    });
  });
}

// Which obj_ids reference a given blob cid (a blob may be referenced by more
// than one envelope only in edge cases like a duplicate upload — normally
// exactly one). Calls thenDo(null, objId[]).
function getObjIdsForBlob(blobCid, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query('SELECT obj_id FROM blob_refs WHERE blob_cid = $1', [blobCid], function (err, result) {
      if (err) return thenDo(err);
      thenDo(null, result.rows.map(function (r) { return r.obj_id; }));
    });
  });
}

// Get the latest envelope version for an objId.
// Calls thenDo(null, envelope) or thenDo(null, null) if not found.
function get(objId, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT envelope FROM objects WHERE obj_id = $1 ORDER BY id DESC LIMIT 1',
      [objId],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        thenDo(null, row ? row.envelope : null);
      }
    );
  });
}

// Get a specific version of an object by its CID.
// Calls thenDo(null, envelope) or thenDo(null, null).
function getVersion(objId, cid, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT envelope FROM objects WHERE obj_id = $1 AND cid = $2',
      [objId, cid],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        thenDo(null, row ? row.envelope : null);
      }
    );
  });
}

// Get all envelope versions for an objId newer than a given prevCid
// (exclusive of the version at prevCid itself).
// If prevCid is null, returns ALL versions from genesis.
// Used by the sync protocol: client sends localCid, server returns delta.
// Calls thenDo(null, envelope[]) in ascending version order.
function getVersionsSince(objId, prevCid, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);

    if (!prevCid) {
      // Return all versions
      pool.query(
        'SELECT envelope FROM objects WHERE obj_id = $1 ORDER BY id ASC',
        [objId],
        function (err, result) {
          if (err) return thenDo(err);
          thenDo(null, result.rows.map(function (r) { return r.envelope; }));
        }
      );
      return;
    }

    // Find the id of the row at prevCid, then return everything after it
    pool.query(
      'SELECT id FROM objects WHERE obj_id = $1 AND cid = $2',
      [objId, prevCid],
      function (err, result) {
        if (err) return thenDo(err);
        var pivotRow = result.rows[0];
        if (!pivotRow) {
          // Client's prevCid not found — return all versions so client can
          // reconcile (may happen after data loss or first sync)
          return getVersionsSince(objId, null, thenDo);
        }
        pool.query(
          'SELECT envelope FROM objects WHERE obj_id = $1 AND id > $2 ORDER BY id ASC',
          [objId, pivotRow.id],
          function (err, result) {
            if (err) return thenDo(err);
            thenDo(null, result.rows.map(function (r) { return r.envelope; }));
          }
        );
      }
    );
  });
}

// List the latest envelope (head version) for every object owned by a DID.
// Excludes type='recovery' (internal system world, never shown in UI).
// Calls thenDo(null, envelope[]).
function listForUser(did, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    // Self-join to get only the latest row per obj_id for this DID
    pool.query(
      'SELECT o.envelope FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects WHERE did = $1 AND type != \'recovery\' GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id',
      [did],
      function (err, result) {
        if (err) return thenDo(err);
        thenDo(null, result.rows.map(function (r) { return r.envelope; }));
      }
    );
  });
}

// List the latest version of every public part, newest first, optionally
// filtered by a partName substring or exact objId match. Same "latest per
// obj_id" join pattern as listForUser/listPostcardsNearby, but scoped to
// type='part' AND visibility='public' across ALL authors instead of one
// did — the cross-user index type/part never had (unlike constellations'
// listPublic or postcards' listPostcardsNearby, which this mirrors).
// Metadata only (no payload/htmlLogo) — callers fetch the full envelope
// via the existing GET /@:handle/:objId route when actually opening a
// result, same lazy-load split every other listing here already uses.
// opts: { limit, cursor, q, tag }
// Calls thenDo(null, { parts: envelopeMetadata[], cursor: String|null }).
function listPublicParts(opts, thenDo) {
  var limit = (opts && opts.limit) || 20;
  var cursor = (opts && opts.cursor) || null;
  var q = (opts && opts.q) || null;
  var tag = (opts && opts.tag) || null;

  withDB(function (err, pool) {
    if (err) return thenDo(err);

    function withPivot(cb) {
      if (!cursor) return cb(null, null);
      pool.query(
        'SELECT MAX(id) AS pivot FROM objects WHERE obj_id = $1 AND type = \'part\'',
        [cursor],
        function (err, result) { cb(err, result && result.rows[0] ? result.rows[0].pivot : null); }
      );
    }

    withPivot(function (err, pivotId) {
      if (err) return thenDo(err);
      var conditions = [];
      var params = [];
      if (q) {
        params.push('%' + _escapeLikePrefix(q) + '%');
        var qPh = '$' + params.length;
        params.push(q);
        var objIdPh = '$' + params.length;
        conditions.push('((o.envelope #>> \'{state,partName}\') ILIKE ' + qPh + ' ESCAPE \'\\\' OR o.obj_id = ' + objIdPh + ')');
      }
      // Category filtering (Inventory browser's "#tag" sidebar entries) —
      // membership test against the JSON array at state.tags via the jsonb
      // `?` containment operator, backed by idx_objects_state_tags_gin.
      if (tag) {
        params.push(tag);
        conditions.push('(o.envelope #> \'{state,tags}\') ? $' + params.length);
      }
      if (pivotId) {
        params.push(pivotId);
        conditions.push('o.id < $' + params.length);
      }
      var whereExtra = conditions.length ? ' AND ' + conditions.join(' AND ') : '';
      var sql =
        'SELECT o.envelope, o.obj_id, o.id FROM objects o' +
        ' INNER JOIN (' +
        '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
        '   WHERE type = \'part\' AND visibility = \'public\'' +
        '   GROUP BY obj_id' +
        ' ) latest ON o.id = latest.max_id' +
        ' WHERE 1=1' + whereExtra +
        ' ORDER BY o.id DESC LIMIT $' + (params.length + 1);
      params.push(limit + 1);

      pool.query(sql, params, function (err, result) {
        if (err) return thenDo(err);
        var rows = result.rows;
        var hasMore = rows.length > limit;
        if (hasMore) rows = rows.slice(0, limit);
        var parts = rows.map(function (r) {
          var env = r.envelope;
          var state = env.state || {};
          return {
            objId: env.objId,
            did: env.did,
            // htmlLogo deliberately omitted — unlike a postcard's state,
            // a part's state.htmlLogo is a full rendered-HTML snapshot
            // (multiple KB per row), which would make a 20-40 row
            // listing response heavy for no reason. Full envelope
            // (htmlLogo included) is one GET /@:handle/:objId away once
            // a specific result is actually opened.
            state: { partName: state.partName, comment: state.comment, tags: state.tags },
            record: { cid: env.record && env.record.cid },
            created: env.created,
            visibility: env.visibility || 'public'
          };
        });
        var nextCursor = hasMore ? rows[rows.length - 1].obj_id : null;
        thenDo(null, { parts: parts, cursor: nextCursor });
      });
    });
  });
}

// Aggregate distinct tags across every latest-version public part, for the
// Inventory browser's "#tag" category sidebar (core/lively/identity/Inventory.js).
// Same "latest row per obj_id, type='part' AND visibility='public'" subquery
// as listPublicParts above, joined against jsonb_array_elements_text() (the
// json_each() equivalent) to explode each part's state.tags array into rows
// before grouping. Capped at 100 tags so a pathological number of distinct
// tags can't blow up the response; ordered by usage count so the most
// useful categories sort first if a caller ever truncates the list.
// Calls thenDo(err, [{tag, count}, ...]).
function listPublicPartTags(thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    var sql =
      'SELECT je AS tag, COUNT(*) AS count FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'part\' AND visibility = \'public\'' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' , jsonb_array_elements_text(COALESCE(o.envelope #> \'{state,tags}\', \'[]\'::jsonb)) je' +
      ' WHERE je IS NOT NULL AND je != \'\'' +
      ' GROUP BY je' +
      ' ORDER BY count DESC, je ASC' +
      ' LIMIT 100';
    pool.query(sql, [], function (err, result) {
      if (err) return thenDo(err);
      // Postgres returns COUNT(*) as a bigint, which node-postgres hands
      // back as a string (to avoid precision loss above 2^53) rather than a
      // JS number the way sqlite3 did — parse it back to a number here so
      // callers see the same type they always have.
      thenDo(null, result.rows.map(function (r) { return { tag: r.tag, count: parseInt(r.count, 10) }; }));
    });
  });
}

// Get the latest profile envelope for a DID.
// Profiles are type:'profile' singletons — one per user.
// Calls thenDo(null, envelope | null).
function getProfileForDid(did, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT envelope FROM objects WHERE did = $1 AND type = \'profile\' ORDER BY id DESC LIMIT 1',
      [did],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        thenDo(null, row ? row.envelope : null);
      }
    );
  });
}

// Get the recovery world envelope for a DID.
// Recovery worlds are type:'recovery' singletons created at registration.
// Calls thenDo(null, envelope | null).
function getRecoveryWorldForDid(did, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT envelope FROM objects WHERE did = $1 AND type = \'recovery\' ORDER BY id DESC LIMIT 1',
      [did],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        thenDo(null, row ? row.envelope : null);
      }
    );
  });
}

// List the full version history (all CIDs) for an objId, ascending.
// Calls thenDo(null, [{ cid, prevCid, createdAt }]).
function listVersions(objId, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT cid, prev_cid, created_at, envelope #>> \'{state,name}\' AS name ' +
      'FROM objects WHERE obj_id = $1 ORDER BY id ASC',
      [objId],
      function (err, result) {
        if (err) return thenDo(err);
        thenDo(null, result.rows.map(function (r) {
          return { cid: r.cid, prevCid: r.prev_cid, createdAt: r.created_at, name: r.name };
        }));
      }
    );
  });
}

// Grant read access to an additional recipient DID on the latest version of
// an object, by appending to record.recipients in place.
//
// Recipients here are an access-control concept only — they gate the
// GET /@:handle/:objId visibility check in IdentityServer.js. They are NOT
// part of the cid hash domain (cid = hash(record.payload) only — see
// SignedSerializer.js / Crypto.computeCid), so granting access cannot be
// represented as a new content-addressed version: the cid would be
// unchanged and collide with idx_obj_cid (obj_id, cid). This updates the
// latest row in place instead of inserting a new version.
//
// For encrypted ('private'/'shared') objects, this only grants the
// recipient permission to fetch the envelope over HTTP — it does not wrap
// a decryption key for them. Actually decrypting requires the owner's
// client to seal a key copy (Crypto.sealForRecipient) and PUT a new
// envelope version; that is out of scope for this ACL-only helper.
//
// Holds the same per-objId advisory lock as put() across its own read
// (of the current recipients array) and write (the appended array) — this
// is a genuine read-modify-write on a whole field, so it needs the lock
// around both steps itself, not just inherited from a lower-level helper;
// unlike setSentAtIfUnset (which delegates its whole read-decide-write to
// put(), already lock-protected), this one can't just call the plain
// public get() before acquiring anything, or two concurrent addRecipient()
// calls for the same objId could each compute a recipients array from the
// same stale snapshot and the second write would silently drop the first's
// addition.
//
// Calls thenDo(err, envelope) with the updated envelope.
function addRecipient(objId, recipientDid, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.connect(function (err, client, release) {
      if (err) return thenDo(err);
      client.query('BEGIN', function (err) {
        if (err) { release(); return thenDo(err); }

        _lockObjIdTx(client, objId, function (err) {
          if (err) return _rollbackAndRelease(client, release, err, thenDo);

          _getLatestTx(client, objId, function (err, envelope) {
            if (err) return _rollbackAndRelease(client, release, err, thenDo);
            if (!envelope) return _rollbackAndRelease(client, release, new Error('addRecipient: object not found: ' + objId), thenDo);

            if (!envelope.record.recipients) envelope.record.recipients = [];
            var already = envelope.record.recipients.some(function (r) {
              return (r.did || r) === recipientDid;
            });
            if (already) {
              return client.query('COMMIT', function (err) {
                release();
                if (err) return thenDo(err);
                thenDo(null, envelope);
              });
            }

            envelope.record.recipients.push({ did: recipientDid });
            if (envelope.visibility === 'private') envelope.visibility = 'shared';

            _updateInPlaceTx(client, envelope, function (err, result) {
              if (err) return _rollbackAndRelease(client, release, err, thenDo);
              client.query('COMMIT', function (err) {
                release();
                if (err) return thenDo(err);
                thenDo(null, result);
              });
            });
          });
        });
      });
    });
  });
}

// Delete all versions of an object that were written after the given cid.
// Used by the revert UI to roll back to a known-good snapshot.
// Calls thenDo(err, { deleted }) where deleted is the row count removed.
function deleteVersionsAfter(objId, cid, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT id FROM objects WHERE obj_id = $1 AND cid = $2',
      [objId, cid],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        if (!row) return thenDo(new Error('deleteVersionsAfter: version not found: ' + cid));
        pool.query(
          'DELETE FROM objects WHERE obj_id = $1 AND id > $2',
          [objId, row.id],
          function (err, delResult) {
            if (err) return thenDo(err);
            thenDo(null, { deleted: delResult.rowCount });
          }
        );
      }
    );
  });
}

// ─── post card queries ────────────────────────────────────────────────────────

// List the latest postcard envelope per objId for a given DID, newest first.
// Excludes deleted cards (state.deleted = true) from the listing.
// opts: { limit: Number, cursor: String|null, q: String|null }
//   cursor is the obj_id of the last item from the previous page (opaque to callers).
//   q — optional title substring filter (§8.1); metadata search only, never
//   record.payload (private/shared payload is ciphertext the server can't
//   search anyway; public payload content-indexing is a standing non-goal).
// Calls thenDo(null, { postcards: [envelope...], cursor: String|null }).
function listPostcardsForUser(did, opts, thenDo) {
  var limit = (opts && opts.limit) || 20;
  var cursor = (opts && opts.cursor) || null;
  var q = (opts && opts.q) || null;
  var qLike = q ? '%' + _escapeLikePrefix(q) + '%' : null;

  withDB(function (err, pool) {
    if (err) return thenDo(err);

    // baseSql always binds did as $1, and qLike (if present) as $2 -- both
    // placeholder numbers are fixed regardless of which branch below runs,
    // since they're baked into baseSql itself; whatever comes after (pivot
    // id / limit) continues numbering from nextPh.
    var baseParams = qLike ? [did, qLike] : [did];
    var nextPh = baseParams.length + 1;

    var baseSql =
      'SELECT o.envelope, o.obj_id, o.id FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE did = $1 AND type = \'postcard\'' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')' +
      // Replies (postcards carrying a replyTo, posted from a comment
      // thread) are not top-level postcards — they belong only in
      // listRepliesForPostcard's own listing, never mixed into a
      // did/constellation's main feed alongside genuine top-level cards.
      '        AND (o.envelope #>> \'{replyTo,objId}\') IS NULL' +
      (qLike ? ' AND (o.envelope #>> \'{state,title}\') ILIKE $2 ESCAPE \'\\\'' : '');

    var params, sql;
    if (cursor) {
      // Pagination: find the id of the cursor row, then take rows with id < that
      pool.query(
        'SELECT MAX(id) AS pivot FROM objects WHERE obj_id = $1 AND did = $2',
        [cursor, did],
        function (err, result) {
          if (err) return thenDo(err);
          var pivotRow = result.rows[0];
          var pivotId = pivotRow ? pivotRow.pivot : null;
          if (pivotId) {
            sql = baseSql + ' AND o.id < $' + nextPh + ' ORDER BY o.id DESC LIMIT $' + (nextPh + 1);
            params = baseParams.concat([pivotId, limit + 1]);
          } else {
            sql = baseSql + ' ORDER BY o.id DESC LIMIT $' + nextPh;
            params = baseParams.concat([limit + 1]);
          }
          _runPostcardQuery(pool, sql, params, limit, thenDo);
        }
      );
    } else {
      sql = baseSql + ' ORDER BY o.id DESC LIMIT $' + nextPh;
      params = baseParams.concat([limit + 1]);
      _runPostcardQuery(pool, sql, params, limit, thenDo);
    }
  });
}

// List the latest postcard envelopes for a constellation, newest first.
// opts: { limit, cursor, q } — same pagination/search shape as
// listPostcardsForUser (q filters on state.title, ILIKE-style).
// Calls thenDo(null, { postcards: [envelopeMetadata...], cursor: String|null }).
function listPostcardsForConstellation(constellation, opts, thenDo) {
  var limit = (opts && opts.limit) || 20;
  var cursor = (opts && opts.cursor) || null;
  var q = (opts && opts.q) || null;
  var qLike = q ? '%' + _escapeLikePrefix(q) + '%' : null;

  withDB(function (err, pool) {
    if (err) return thenDo(err);

    var baseParams = qLike ? [constellation, qLike] : [constellation];
    var nextPh = baseParams.length + 1;

    var baseSql =
      'SELECT o.envelope, o.obj_id, o.id FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'postcard\'' +
      '         AND (envelope ->> \'constellation\') = $1' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')' +
      // System-generated cards (join requests riding the same postal rail
      // as everything else, ConstellationDesignSpec.md §4.2) belong in
      // controllers' inboxes, not the public constellation feed. Room-level
      // join requests (state.kind:'room-join-request', see
      // ConstellationLounge.js's _requestRoomAccess) ride the same rail and
      // were missing from this exclusion, so they rendered as ordinary
      // postcards in the feed. Room chat messages (state.kind:'room-message',
      // RoomView.js, see listMessagesForRoom below) ride it too — same
      // exclusion, or every chat line would flood the constellation's
      // public postcard reel.
      '        AND ((o.envelope #>> \'{state,kind}\') IS NULL' +
      '             OR (o.envelope #>> \'{state,kind}\') NOT IN' +
      '                 (\'constellation-join-request\', \'room-join-request\', \'room-message\'))' +
      // Replies (comment-thread postcards carrying a replyTo) are not
      // top-level postcards either — confirmed live via objects.db that
      // every reply also carries this constellation's name, so without
      // this filter every comment-thread reply doubled as its own entry
      // in the postcard turnover reel (ConstellationLounge.js's _fetchFeed).
      // listRepliesForPostcard below is the only listing that should ever
      // surface them.
      '        AND (o.envelope #>> \'{replyTo,objId}\') IS NULL' +
      (qLike ? ' AND (o.envelope #>> \'{state,title}\') ILIKE $2 ESCAPE \'\\\'' : '');

    var params, sql;
    if (cursor) {
      pool.query(
        'SELECT MAX(id) AS pivot FROM objects WHERE obj_id = $1' +
        '  AND type = \'postcard\'',
        [cursor],
        function (err, result) {
          if (err) return thenDo(err);
          var pivotRow = result.rows[0];
          var pivotId = pivotRow ? pivotRow.pivot : null;
          if (pivotId) {
            sql = baseSql + ' AND o.id < $' + nextPh + ' ORDER BY o.id DESC LIMIT $' + (nextPh + 1);
            params = baseParams.concat([pivotId, limit + 1]);
          } else {
            sql = baseSql + ' ORDER BY o.id DESC LIMIT $' + nextPh;
            params = baseParams.concat([limit + 1]);
          }
          _runPostcardQuery(pool, sql, params, limit, thenDo);
        }
      );
    } else {
      sql = baseSql + ' ORDER BY o.id DESC LIMIT $' + nextPh;
      params = baseParams.concat([limit + 1]);
      _runPostcardQuery(pool, sql, params, limit, thenDo);
    }
  });
}

// List the latest room-message postcard envelopes for a room, newest first
// — same "latest version per obj_id" join shape as listPostcardsForConstellation
// (RoomView.js's chat rides the same objects-table/postal rail every other
// postcard uses: state.kind:'room-message', state.roomId:<roomId>, rather
// than a dedicated messages table), scoped to a roomId instead of a
// constellation. Metadata only (state.title, the auto-extracted first-block
// text — plenty for a short chat line, capped at 200 chars same as any
// other postcard's title extraction) — no separate payload fetch needed per
// message, keeping a chat page's listing call as cheap as any other feed
// listing here.
// opts: { limit, cursor } — same pagination shape as listPostcardsForConstellation.
// Calls thenDo(null, { postcards: [envelopeMetadata...], cursor: String|null }).
function listMessagesForRoom(roomId, opts, thenDo) {
  var limit = (opts && opts.limit) || 50;
  var cursor = (opts && opts.cursor) || null;

  withDB(function (err, pool) {
    if (err) return thenDo(err);

    var baseSql =
      'SELECT o.envelope, o.obj_id, o.id FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'postcard\'' +
      '         AND (envelope #>> \'{state,kind}\') = \'room-message\'' +
      '         AND (envelope #>> \'{state,roomId}\') = $1' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')';

    var params, sql;
    if (cursor) {
      pool.query(
        'SELECT MAX(id) AS pivot FROM objects WHERE obj_id = $1 AND type = \'postcard\'',
        [cursor],
        function (err, result) {
          if (err) return thenDo(err);
          var pivotRow = result.rows[0];
          var pivotId = pivotRow ? pivotRow.pivot : null;
          if (pivotId) {
            sql = baseSql + ' AND o.id < $2 ORDER BY o.id DESC LIMIT $3';
            params = [roomId, pivotId, limit + 1];
          } else {
            sql = baseSql + ' ORDER BY o.id DESC LIMIT $2';
            params = [roomId, limit + 1];
          }
          _runPostcardQuery(pool, sql, params, limit, thenDo);
        }
      );
    } else {
      sql = baseSql + ' ORDER BY o.id DESC LIMIT $2';
      params = [roomId, limit + 1];
      _runPostcardQuery(pool, sql, params, limit, thenDo);
    }
  });
}

// Looks up a wiki page's objId by name within a constellation (a wiki page
// is a type: 'wikipage' envelope, addressed by state.wikiName). Used by
// GET /c/:name/wiki/:pageName to resolve a human-friendly page name to the
// objId every other read/write route already operates on — wiki pages
// remain addressable both ways (by name here, or directly via
// /@handle/objId or /c/:name/objId), per the original ontology. Callers
// still need a follow-up get(objId, ...) for the full envelope — this only
// resolves the name, same division of labor as every other lookup-then-get
// pattern in this module.
// Calls thenDo(null, objId | null).
function getWikiPageObjId(constellation, wikiName, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT o.obj_id FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'wikipage\'' +
      '         AND (envelope ->> \'constellation\') = $1' +
      '         AND (envelope #>> \'{state,wikiName}\') = $2' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')' +
      ' ORDER BY o.id DESC LIMIT 1',
      [constellation, wikiName],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        thenDo(null, row ? row.obj_id : null);
      }
    );
  });
}

// Lists the latest version of every wiki page in a constellation, for the
// wiki index (GET /c/:name/wiki). Same "latest version per obj_id" join
// shape as listPostcardsForConstellation, filtered on type = 'wikipage'
// instead. No pagination — wiki-page counts per constellation are small;
// add it if that stops being true.
// updatedAt is the latest version row's created_at (an edit is a new row,
// see WikiSerializer.js); createdAt is a second join on the same obj_id
// grouping by MIN(created_at) instead of MAX(id) — the genesis row's own
// timestamp, which the "latest version" join above discards. Both are
// needed so the wiki index's sort-by dropdown (WikiIndex.js) can offer
// "last modified" and "last created" as genuinely different orderings —
// for a page that's never been edited the two are equal anyway.
// category/tags are pulled the same way listWikiPagesForUser's version
// below does — WikiIndex.js's right-hand categories/tags panel needs them
// for constellation-scoped wikis too, not just personal ones.
// Calls thenDo(null, [{ objId, wikiName, category, tags, updatedAt, createdAt }, ...]).
function listWikiPages(constellation, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT o.obj_id, o.created_at AS updated_at, genesis.created_at AS created_at,' +
      '       o.envelope #>> \'{state,wikiName}\' AS wiki_name,' +
      '       o.envelope #>> \'{state,category}\' AS category,' +
      '       o.envelope #> \'{state,tags}\' AS tags_json' +
      ' FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'wikipage\'' +
      '         AND (envelope ->> \'constellation\') = $1' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MIN(created_at) AS created_at FROM objects' +
      '   WHERE type = \'wikipage\'' +
      '         AND (envelope ->> \'constellation\') = $2' +
      '   GROUP BY obj_id' +
      ' ) genesis ON genesis.obj_id = o.obj_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')' +
      ' ORDER BY wiki_name ASC',
      [constellation, constellation],
      function (err, result) {
        if (err) return thenDo(err);
        thenDo(null, (result.rows || []).map(function (r) {
          return {
            objId: r.obj_id, wikiName: r.wiki_name, category: r.category || null, tags: r.tags_json || [],
            updatedAt: r.updated_at, createdAt: r.created_at,
          };
        }));
      }
    );
  });
}

// Personal (home-world) counterpart to getWikiPageObjId — resolves a wiki
// page by human-friendly name under a user's own did, instead of within a
// constellation. Same "latest version per obj_id" shape, keyed on the did
// column directly (no envelope extraction needed for it, unlike
// constellation which only lives inside the envelope JSON).
//
// constellation IS NULL is a real, load-bearing filter here, not a no-op:
// this did may also own constellation-scoped wikipage envelopes (authored
// as a member with write access, or in a constellation they control) —
// those belong to the constellation, not to this user's personal wiki, and
// must not resolve/list here. Confirmed live: without this filter,
// getWikiPageObjIdForUser/listWikiPagesForUser below returned every
// wikipage envelope this did ever authored regardless of constellation,
// which put a constellation's test pages in the personal index. constella-
// tion is fixed at genesis and never changes across a page's versions (see
// WikiSerializer.js), so filtering it in this subquery (rather than only
// in the outer WHERE) is equivalent and cheaper.
function getWikiPageObjIdForUser(did, wikiName, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT o.obj_id FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'wikipage\'' +
      '         AND did = $1' +
      '         AND (envelope ->> \'constellation\') IS NULL' +
      '         AND (envelope #>> \'{state,wikiName}\') = $2' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')' +
      ' ORDER BY o.id DESC LIMIT 1',
      [did, wikiName],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        thenDo(null, row ? row.obj_id : null);
      }
    );
  });
}

// Personal (home-world) counterpart to listWikiPages — every wiki page
// owned by a user's own did, not tied to any constellation, for the
// personal wiki index (GET /@:handle/wiki). Same no-pagination precedent as
// listWikiPages (small per-scope counts). Also surfaces category/tags for
// the index cards — listWikiPages doesn't need these today but there's no
// reason the personal listing shouldn't carry them. Same updatedAt/createdAt
// two-join shape as listWikiPages above — see that function's comment.
// Calls thenDo(null, [{ objId, wikiName, category, tags, updatedAt, createdAt }, ...]).
function listWikiPagesForUser(did, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT o.obj_id, o.created_at AS updated_at, genesis.created_at AS created_at,' +
      '       o.envelope #>> \'{state,wikiName}\' AS wiki_name,' +
      '       o.envelope #>> \'{state,category}\' AS category,' +
      '       o.envelope #> \'{state,tags}\' AS tags_json' +
      ' FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'wikipage\'' +
      '         AND did = $1' +
      '         AND (envelope ->> \'constellation\') IS NULL' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MIN(created_at) AS created_at FROM objects' +
      '   WHERE type = \'wikipage\'' +
      '         AND did = $2' +
      '         AND (envelope ->> \'constellation\') IS NULL' +
      '   GROUP BY obj_id' +
      ' ) genesis ON genesis.obj_id = o.obj_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')' +
      ' ORDER BY wiki_name ASC',
      [did, did],
      function (err, result) {
        if (err) return thenDo(err);
        thenDo(null, (result.rows || []).map(function (r) {
          return {
            objId: r.obj_id, wikiName: r.wiki_name, category: r.category || null,
            tags: r.tags_json || [], updatedAt: r.updated_at, createdAt: r.created_at,
          };
        }));
      }
    );
  });
}

// Escapes SQL LIKE/ILIKE wildcards (% and _) in a string that's about to be
// used as a LIKE prefix — Plus Codes' own alphabet ('23456789CFGHJMPQRVWX'
// plus '+'/'0') never contains either character, but a caller-supplied
// query param shouldn't be trusted to actually be a well-formed Plus Code by
// the time it reaches SQL, so escape defensively rather than relying on
// that implicitly.
function _escapeLikePrefix(s) {
  return String(s).replace(/[%_]/g, '\\$&');
}

// List latest public postcard envelopes whose state.location Plus Code
// starts with the given (already-floored) prefix — Plus Codes are
// naturally prefix-friendly: a longer shared prefix means a smaller shared
// grid cell, so this needs no lat/lng bounding-box math. Only
// visibility:'public' postcards are eligible (there is no "list all
// private/shared postcards near X" — that would defeat the point of
// marking them private).
// opts: { limit, cursor } — same pagination shape as listPostcardsForUser.
// Calls thenDo(null, { postcards: [envelopeMetadata...], cursor }).
function listPostcardsNearby(codePrefix, opts, thenDo) {
  var limit = (opts && opts.limit) || 20;
  var cursor = (opts && opts.cursor) || null;
  var likePrefix = _escapeLikePrefix(codePrefix) + '%';

  withDB(function (err, pool) {
    if (err) return thenDo(err);

    var baseSql =
      'SELECT o.envelope, o.obj_id, o.id FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'postcard\' AND visibility = \'public\'' +
      '         AND (envelope #>> \'{state,location}\') ILIKE $1 ESCAPE \'\\\'' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')';

    var params, sql;
    if (cursor) {
      pool.query(
        'SELECT MAX(id) AS pivot FROM objects WHERE obj_id = $1' +
        '  AND type = \'postcard\'',
        [cursor],
        function (err, result) {
          if (err) return thenDo(err);
          var pivotRow = result.rows[0];
          var pivotId = pivotRow ? pivotRow.pivot : null;
          if (pivotId) {
            sql = baseSql + ' AND o.id < $2 ORDER BY o.id DESC LIMIT $3';
            params = [likePrefix, pivotId, limit + 1];
          } else {
            sql = baseSql + ' ORDER BY o.id DESC LIMIT $2';
            params = [likePrefix, limit + 1];
          }
          _runPostcardQuery(pool, sql, params, limit, thenDo);
        }
      );
    } else {
      sql = baseSql + ' ORDER BY o.id DESC LIMIT $2';
      params = [likePrefix, limit + 1];
      _runPostcardQuery(pool, sql, params, limit, thenDo);
    }
  });
}

// List reply envelopes for a parent objId (postcards whose replyTo.objId matches).
// Returns metadata-only (no payload) for the listing; caller fetches full envelope on open.
// Visibility filtering is the caller's responsibility (done in the route handler).
// opts: { limit, cursor, q, sort }
//   q — optional title substring filter (§8.1), same ILIKE approach as
//   listPostcardsForUser.
//   sort — 'new' (default, unchanged: newest first, cursor-paginated) or
//   'top' (§8.2: ordered by reaction count via a LEFT JOIN against
//   postcard_reactions). 'top' deliberately doesn't support cursor
//   pagination — reply threads aren't expected to be long enough to need
//   it yet, and a stable cursor over a COUNT-ordered result would need a
//   compound (count, id) cursor instead of the simple id-based one every
//   other listing here uses; always returns cursor: null.
// Calls thenDo(null, { postcards: [envelopeMetadata...], cursor: String|null })
// — same shape key as every other listing here (despite the function name);
// the /replies route reads result.postcards, not result.replies.
function listRepliesForPostcard(parentObjId, opts, thenDo) {
  var limit = (opts && opts.limit) || 20;
  var cursor = (opts && opts.cursor) || null;
  var q = (opts && opts.q) || null;
  var qLike = q ? '%' + _escapeLikePrefix(q) + '%' : null;
  var sort = (opts && opts.sort) === 'top' ? 'top' : 'new';

  withDB(function (err, pool) {
    if (err) return thenDo(err);

    var baseParams = qLike ? [parentObjId, qLike] : [parentObjId];
    var nextPh = baseParams.length + 1;

    var baseSql =
      'SELECT o.envelope, o.obj_id, o.id FROM objects o' +
      ' INNER JOIN (' +
      '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
      '   WHERE type = \'postcard\'' +
      '         AND (envelope #>> \'{replyTo,objId}\') = $1' +
      '   GROUP BY obj_id' +
      ' ) latest ON o.id = latest.max_id' +
      ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
      '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')' +
      (qLike ? ' AND (o.envelope #>> \'{state,title}\') ILIKE $2 ESCAPE \'\\\'' : '');

    if (sort === 'top') {
      var topSql =
        'SELECT o.envelope, o.obj_id, o.id, COUNT(pr.obj_id) AS reaction_count' +
        ' FROM objects o' +
        ' INNER JOIN (' +
        '   SELECT obj_id, MAX(id) AS max_id FROM objects' +
        '   WHERE type = \'postcard\'' +
        '         AND (envelope #>> \'{replyTo,objId}\') = $1' +
        '   GROUP BY obj_id' +
        ' ) latest ON o.id = latest.max_id' +
        ' LEFT JOIN postcard_reactions pr ON pr.obj_id = o.obj_id' +
        ' WHERE ((o.envelope #>> \'{state,deleted}\') IS NULL' +
        '        OR (o.envelope #>> \'{state,deleted}\') <> \'true\')' +
        (qLike ? ' AND (o.envelope #>> \'{state,title}\') ILIKE $2 ESCAPE \'\\\'' : '') +
        // Grouping by o.id alone (objects' own primary key) is enough for
        // Postgres to allow selecting o.envelope/o.obj_id from the same
        // table without listing them too, via its functional-dependency
        // extension to GROUP BY -- SQLite's much looser GROUP BY rules
        // (picks an arbitrary matching row for ungrouped columns) let the
        // original query get away with `GROUP BY o.obj_id` alone, which
        // Postgres would reject outright.
        ' GROUP BY o.id' +
        ' ORDER BY reaction_count DESC, o.id DESC' +
        ' LIMIT $' + nextPh;
      return _runPostcardQuery(pool, topSql, baseParams.concat([limit]), limit, thenDo);
    }

    var params, sql;
    if (cursor) {
      pool.query(
        'SELECT MAX(id) AS pivot FROM objects WHERE obj_id = $1 AND type = \'postcard\'',
        [cursor],
        function (err, result) {
          if (err) return thenDo(err);
          var pivotRow = result.rows[0];
          var pivotId = pivotRow ? pivotRow.pivot : null;
          if (pivotId) {
            _runPostcardQuery(pool,
              baseSql + ' AND o.id < $' + nextPh + ' ORDER BY o.id DESC LIMIT $' + (nextPh + 1),
              baseParams.concat([pivotId, limit + 1]), limit, thenDo);
          } else {
            _runPostcardQuery(pool, baseSql + ' ORDER BY o.id DESC LIMIT $' + nextPh,
              baseParams.concat([limit + 1]), limit, thenDo);
          }
        }
      );
    } else {
      _runPostcardQuery(pool, baseSql + ' ORDER BY o.id DESC LIMIT $' + nextPh, baseParams.concat([limit + 1]), limit, thenDo);
    }
  });
}

// Shared helper: runs a postcard listing SQL query and shapes the result into
// { postcards: [metadataOnly...], cursor } (spec §7.1 feed shape).
function _runPostcardQuery(pool, sql, params, limit, thenDo) {
  pool.query(sql, params, function (err, result) {
    if (err) return thenDo(err);
    var rows = result.rows;
    var hasMore = rows.length > limit;
    if (hasMore) rows = rows.slice(0, limit);
    var postcards = rows.map(function (r) {
      var env = r.envelope;
      // Return metadata only — not the full payload (spec §7.1)
      return {
        objId: env.objId,
        did: env.did,
        state: env.state || {},
        record: { cid: env.record && env.record.cid },
        created: env.created,
        constellation: env.constellation || null,
        replyTo: env.replyTo || null,
        visibility: env.visibility || 'public',
        recipients: (env.record && env.record.recipients) || []
      };
    });
    var nextCursor = hasMore ? rows[rows.length - 1].obj_id : null;
    thenDo(null, { postcards: postcards, cursor: nextCursor });
  });
}

// ─── part aliases (Roadmap.md §3, "Phase 2 — Parts Name Aliasing") ────────────

// Point (did, aliasName) at objId, overwriting whatever it pointed to
// before — an upsert, since PRIMARY KEY (did, alias_name) means an author
// can only have one part named e.g. "MyButton" at a time, and republishing
// under that name should repoint the alias rather than error. Called by
// put() itself (see above) whenever a type:'part' envelope carries a
// state.partName, so no client code needs to know this table exists — the
// alias table stays a purely server-side resolution convenience, per
// Roadmap.md §3.
// Calls thenDo(err).
function upsertPartAlias(did, aliasName, objId, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'INSERT INTO part_aliases (did, alias_name, obj_id, updated_at) VALUES ($1, $2, $3, $4)' +
      ' ON CONFLICT (did, alias_name) DO UPDATE SET obj_id = EXCLUDED.obj_id, updated_at = EXCLUDED.updated_at',
      [did, aliasName, objId, new Date().toISOString()],
      function (err) { thenDo(err || null); }
    );
  });
}

// Resolve a human-readable part name to its current objId for a given
// author DID. Calls thenDo(null, objId | null).
function resolvePartAlias(did, aliasName, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT obj_id FROM part_aliases WHERE did = $1 AND alias_name = $2',
      [did, aliasName],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        thenDo(null, row ? row.obj_id : null);
      }
    );
  });
}

// ─── postcard reactions (PostcardDesignSpec-v2.md §5.1) ────────────────────────

// Upsert (replace) the caller's own reaction on a postcard. PRIMARY KEY
// (obj_id, did) means a second reaction from the same did overwrites the
// first rather than stacking.
// Calls thenDo(err).
function upsertReaction(objId, did, emoji, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'INSERT INTO postcard_reactions (obj_id, did, emoji, created_at) VALUES ($1, $2, $3, $4)' +
      ' ON CONFLICT (obj_id, did) DO UPDATE SET emoji = EXCLUDED.emoji, created_at = EXCLUDED.created_at',
      [objId, did, emoji, new Date().toISOString()],
      function (err) { thenDo(err || null); }
    );
  });
}

// Remove the caller's own reaction, if any. Idempotent.
// Calls thenDo(err).
function deleteReaction(objId, did, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'DELETE FROM postcard_reactions WHERE obj_id = $1 AND did = $2',
      [objId, did],
      function (err) { thenDo(err || null); }
    );
  });
}

// All reactions on a postcard. Calls thenDo(null, [{ did, emoji }]).
function getReactionsForObjId(objId, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT did, emoji FROM postcard_reactions WHERE obj_id = $1',
      [objId],
      function (err, result) { thenDo(err, result ? result.rows : []); }
    );
  });
}

// ─── postcard send-freeze (PostcardDesignSpec-v2.md §2.5) ─────────────────────

// Stamps state.sentAt on an objId's latest version, server-side, the first
// time it's delivered to a DID other than its own author's — a one-way
// flag that's never cleared and never reset once set (a no-op if already
// present, so a later self-send after a real send can't look like it
// "un-freezes" anything). Reuses put()'s existing same-cid/metadata-changed
// path (record.payload is untouched, only state differs) rather than a
// bespoke UPDATE, so this goes through the same in-place-update code every
// other state-only change already does — including put()'s own advisory
// lock, since the actual read-decide-write happens inside put() itself;
// this function's own get() below is only used to short-circuit the common
// case (sentAt already set) without paying for a lock+transaction at all.
// Calls thenDo(err, envelope) — envelope is the (possibly already-frozen)
// current version either way.
function setSentAtIfUnset(objId, thenDo) {
  get(objId, function (err, envelope) {
    if (err) return thenDo(err);
    if (!envelope) return thenDo(new Error('setSentAtIfUnset: object not found: ' + objId));
    if (envelope.state && envelope.state.sentAt) return thenDo(null, envelope);

    envelope.state = Object.assign({}, envelope.state, { sentAt: new Date().toISOString() });
    put(envelope, function (err) {
      if (err) return thenDo(err);
      thenDo(null, envelope);
    });
  });
}

// ─── postcard mailbox hide (PostcardDesignSpec-v2.md §6.3, Layer 1) ───────────

// Hide an objId from `did`'s own mailbox views — idempotent (a second hide
// of an already-hidden card is a no-op, keeping the original hidden_at
// rather than refreshing it). Never touches the envelope itself; this is
// what makes it safe to call for a card `did` didn't author (a received
// card, say) — no ownership check happens here, callers gate on "is this
// DID's own mailbox" instead (§6.3: "you can only hide something from your
// own mailbox").
// Calls thenDo(err).
function hidePostcardForDid(did, objId, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'INSERT INTO postcard_mailbox_hidden (did, obj_id, hidden_at) VALUES ($1, $2, $3)' +
      ' ON CONFLICT (did, obj_id) DO NOTHING',
      [did, objId, new Date().toISOString()],
      function (err) { thenDo(err || null); }
    );
  });
}

// Every objId `did` has hidden from their own mailbox. Calls thenDo(null, objId[]).
function getHiddenObjIdsForDid(did, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT obj_id FROM postcard_mailbox_hidden WHERE did = $1',
      [did],
      function (err, result) {
        if (err) return thenDo(err);
        thenDo(null, result.rows.map(function (r) { return r.obj_id; }));
      }
    );
  });
}

// ─── settings ─────────────────────────────────────────────────────────────────

// Get the settings envelope for a DID. Returns null if none exists yet.
// The caller should create a default settings envelope if null is returned.
// Calls thenDo(null, envelope | null).
function getSettingsForDid(did, thenDo) {
  withDB(function (err, pool) {
    if (err) return thenDo(err);
    pool.query(
      'SELECT envelope FROM objects WHERE did = $1 AND type = \'settings\' ORDER BY id DESC LIMIT 1',
      [did],
      function (err, result) {
        if (err) return thenDo(err);
        var row = result.rows[0];
        thenDo(null, row ? row.envelope : null);
      }
    );
  });
}

// §8.1 title search for inbox/deliveries records — unlike the SQL-backed
// listings above, a JSONL delivery record ({objId, senderDid, sentAt, ...})
// doesn't carry the postcard's title itself, so there's no LIKE clause to
// add to a query that doesn't exist. Instead, for each candidate record,
// look up its objId's current title from the objects table and keep only
// the matches — one get() per record, run in parallel. Called with the full
// (already hidden/status-filtered) record list, before pagination, so a
// page never comes back short just because some of its rows didn't match.
// Only invoked when q is actually set — no extra DB round trips on the
// unfiltered path.
// Calls thenDo(null, records) in the same order as the input.
function _filterRecordsByTitle(records, q, thenDo) {
  if (!q) return thenDo(null, records);
  if (!records.length) return thenDo(null, []);
  var qLower = q.toLowerCase();
  var remaining = records.length;
  var firstErr = null;
  var matched = new Array(records.length);
  records.forEach(function (rec, i) {
    get(rec.objId, function (err, envelope) {
      if (err) firstErr = firstErr || err;
      var title = (envelope && envelope.state && envelope.state.title) || '';
      matched[i] = title.toLowerCase().indexOf(qLower) !== -1 ? rec : undefined;
      if (--remaining === 0) {
        if (firstErr) return thenDo(firstErr);
        thenDo(null, matched.filter(function (r) { return r !== undefined; }));
      }
    });
  });
}

// ─── inbox ────────────────────────────────────────────────────────────────────

// Inbox records are stored as a per-handle newline-delimited JSON log
// (not in the objects table — delivery references, not versioned
// envelopes). Location: <WORKSPACE_LK>/identity/inbox/<handle>.jsonl
//
// Out of scope for the Postgres migration entirely — this section and
// deliveries below are unchanged, still plain local-filesystem I/O.

var _inboxDir = null;
function _getInboxDir() {
  if (_inboxDir) return _inboxDir;
  _inboxDir = path.join(
    process.env.WORKSPACE_LK || process.cwd(),
    'identity', 'inbox'
  );
  return _inboxDir;
}

// Append a delivery record to a recipient's inbox.
// record: { objId, senderDid, sentAt }
// Calls thenDo(err).
function putInboxRecord(recipientHandle, record, thenDo) {
  var fs = require('fs');
  var dir = _getInboxDir();
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  var file = path.join(dir, recipientHandle + '.jsonl');
  var line = JSON.stringify(record) + '\n';
  fs.appendFile(file, line, function (err) { thenDo(err || null); });
}

// List delivery records for a handle, newest first, paginated.
// opts: { limit, offset, hiddenObjIds, q }
//   hiddenObjIds — objId[] to exclude (§6.3 Layer 1) — filtered before
//   pagination (not after), same as every SQL-backed listing's WHERE
//   clause does for state.deleted, so a page never comes back short just
//   because some of its rows were hidden.
//   q — optional title substring filter (§8.1) — see _filterRecordsByTitle.
// Calls thenDo(null, { records: [...], cursor: Number|null }).
function listInboxForHandle(handle, opts, thenDo) {
  var fs = require('fs');
  var limit = (opts && opts.limit) || 20;
  var offset = (opts && opts.offset) || 0;
  var hiddenObjIds = (opts && opts.hiddenObjIds) || null;
  var q = (opts && opts.q) || null;
  var file = path.join(_getInboxDir(), handle + '.jsonl');
  if (!fs.existsSync(file)) return thenDo(null, { records: [], cursor: null });
  fs.readFile(file, 'utf8', function (err, text) {
    if (err) return thenDo(err);
    var lines = text.split('\n').filter(Boolean);
    lines.reverse(); // newest first
    var records = lines.map(function (l) {
      try { return JSON.parse(l); } catch (e) { return null; }
    }).filter(Boolean);
    if (hiddenObjIds && hiddenObjIds.length) {
      records = records.filter(function (r) { return hiddenObjIds.indexOf(r.objId) === -1; });
    }
    _filterRecordsByTitle(records, q, function (err, filtered) {
      if (err) return thenDo(err);
      var page = filtered.slice(offset, offset + limit);
      var nextOffset = offset + limit < filtered.length ? offset + limit : null;
      _enrichWithConstellationTag(page, function (err, enriched) {
        if (err) return thenDo(err);
        thenDo(null, { records: enriched, cursor: nextOffset });
      });
    });
  });
}

// Merges envelope.constellation/envelope.state.kind onto each record on the
// *returned page only* (bounded to `limit`, never the full inbox log) — so
// PostCardMailbox.js can show a "c/<name>" badge distinguishing e.g. a
// constellation-join-request card from a regular postcard without a
// separate per-row fetch when the list first renders. Same bounded-cost
// per-page envelope lookup _filterRecordsByTitle above already does for
// search; this just always runs, not only when q is set.
function _enrichWithConstellationTag(page, thenDo) {
  if (!page.length) return thenDo(null, page);
  var remaining = page.length;
  var firstErr = null;
  page.forEach(function (rec) {
    get(rec.objId, function (err, envelope) {
      if (err) firstErr = firstErr || err;
      if (envelope) {
        rec.constellation = envelope.constellation || null;
        rec.kind = (envelope.state && envelope.state.kind) || null;
      }
      if (--remaining === 0) thenDo(firstErr, page);
    });
  });
}

// ─── deliveries (sender-side outbound log) ────────────────────────────────────
//
// Mirrors the inbox pattern: a per-sender newline-delimited JSON log.
// Location: <WORKSPACE_LK>/identity/deliveries/<senderHandle>.jsonl
// Each record: { objId, recipientHandle, sentAt, status: 'delivered'|'returned' }
//
// The status field matches the postal model in PostcardDesignSpec.md §2.3:
//   'delivered' — POST /@:handle/inbox succeeded (recipient accepted the card)
//   'returned'  — server returned the postal rejection (blocked/unknown handle)
//
// The reason for a 'returned' delivery is never stored — per the spec's
// anti-leak invariant the sender already knows the postal response text and
// recording a richer reason here would not add information they don't have.

var _deliveriesDir = null;
function _getDeliveriesDir() {
  if (_deliveriesDir) return _deliveriesDir;
  _deliveriesDir = path.join(
    process.env.WORKSPACE_LK || process.cwd(),
    'identity', 'deliveries'
  );
  return _deliveriesDir;
}

// Append an outbound delivery record to the sender's deliveries log.
// record: { objId, recipientHandle, sentAt, status: 'delivered'|'returned' }
// Calls thenDo(err). Fire-and-forget safe — never blocks the HTTP response.
function putDeliveryRecord(senderHandle, record, thenDo) {
  var fs  = require('fs');
  var dir = _getDeliveriesDir();
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  var file = path.join(dir, senderHandle + '.jsonl');
  var line = JSON.stringify(record) + '\n';
  fs.appendFile(file, line, function (err) { thenDo(err || null); });
}

// List outbound delivery records for a sender, newest first, paginated.
// opts: { limit, offset, status, hiddenObjIds }
//   status — filters to 'delivered' or 'returned' when set.
//   hiddenObjIds — objId[] to exclude (§6.3 Layer 1), filtered before
//   pagination, same reasoning as listInboxForHandle above.
// Calls thenDo(null, { records: [...], cursor: Number|null }).
function listDeliveriesForHandle(senderHandle, opts, thenDo) {
  var fs     = require('fs');
  var limit  = (opts && opts.limit)  || 20;
  var offset = (opts && opts.offset) || 0;
  var status = (opts && opts.status) || null;
  var hiddenObjIds = (opts && opts.hiddenObjIds) || null;
  var q      = (opts && opts.q) || null;
  var file   = path.join(_getDeliveriesDir(), senderHandle + '.jsonl');
  if (!fs.existsSync(file)) return thenDo(null, { records: [], cursor: null });
  fs.readFile(file, 'utf8', function (err, text) {
    if (err) return thenDo(err);
    var lines = text.split('\n').filter(Boolean);
    lines.reverse(); // newest first
    var records = lines.map(function (l) {
      try { return JSON.parse(l); } catch (e) { return null; }
    }).filter(Boolean);
    if (status) records = records.filter(function (r) { return r.status === status; });
    if (hiddenObjIds && hiddenObjIds.length) {
      records = records.filter(function (r) { return hiddenObjIds.indexOf(r.objId) === -1; });
    }
    _filterRecordsByTitle(records, q, function (err, filtered) {
      if (err) return thenDo(err);
      var page       = filtered.slice(offset, offset + limit);
      var nextOffset = offset + limit < filtered.length ? offset + limit : null;
      thenDo(null, { records: page, cursor: nextOffset });
    });
  });
}

module.exports = {
  withDB:                        withDB,
  put:                           put,
  get:                           get,
  getVersion:                    getVersion,
  getVersionsSince:              getVersionsSince,
  listForUser:                   listForUser,
  listPublicParts:               listPublicParts,
  listPublicPartTags:            listPublicPartTags,
  getProfileForDid:              getProfileForDid,
  getRecoveryWorldForDid:        getRecoveryWorldForDid,
  getSettingsForDid:             getSettingsForDid,
  listVersions:                  listVersions,
  deleteVersionsAfter:           deleteVersionsAfter,
  getObjIdsForBlob:              getObjIdsForBlob,
  addRecipient:                  addRecipient,
  upsertPartAlias:               upsertPartAlias,
  resolvePartAlias:              resolvePartAlias,
  listPostcardsForUser:          listPostcardsForUser,
  listPostcardsForConstellation: listPostcardsForConstellation,
  listMessagesForRoom:           listMessagesForRoom,
  getWikiPageObjId:              getWikiPageObjId,
  listWikiPages:                 listWikiPages,
  getWikiPageObjIdForUser:       getWikiPageObjIdForUser,
  listWikiPagesForUser:          listWikiPagesForUser,
  listPostcardsNearby:           listPostcardsNearby,
  listRepliesForPostcard:        listRepliesForPostcard,
  upsertReaction:                upsertReaction,
  deleteReaction:                deleteReaction,
  getReactionsForObjId:          getReactionsForObjId,
  hidePostcardForDid:            hidePostcardForDid,
  getHiddenObjIdsForDid:         getHiddenObjIdsForDid,
  setSentAtIfUnset:              setSentAtIfUnset,
  putInboxRecord:                putInboxRecord,
  listInboxForHandle:            listInboxForHandle,
  putDeliveryRecord:             putDeliveryRecord,
  listDeliveriesForHandle:       listDeliveriesForHandle,
};
