/**
 * core/lib/pyodide/pyodide-worker.js
 *
 * Hand-written Worker entry point for the wiki's Python code-cell feature
 * (CodeEditorSpec.md §2.3). NOT generated by scripts/copy-pyodide-libs.js —
 * that script only vendors the runtime/package files this script loads.
 * Runs inside a dedicated Worker; core/lively/identity/PyodideWorker.js owns
 * exactly one per wiki page (all code_cell nodes on that page share it —
 * CodeEditorSpec.md §2.3's decided cell-isolation model). Modeled on
 * core/lively/jenga3d/occt-worker-src.js's shape: a thin protocol layer
 * wrapped around a vendored WASM runtime.
 *
 * Protocol (postMessage, plain JSON-able objects):
 *   in:  {op:'init'}
 *   out: {ok:true, op:'init'}  or  {ok:false, op:'init', error}
 *   in:  {id, op:'run', source}
 *   out: {id, ok:true,  stdout, stderr, result, images}
 *        {id, ok:false, stdout, stderr, error, images}
 *   (images: array of base64 PNG strings, one per matplotlib figure left
 *   open by the cell's source, captured even on error — a traceback can
 *   happen after a plot was already drawn, and the plot is still worth
 *   showing.)
 *
 * A Worker has no canvas/DOM, so matplotlib is forced onto the headless Agg
 * backend during init, before any user code can import matplotlib.pyplot.
 * plt.show() is a no-op under Agg (same as any headless backend) — figures
 * are captured explicitly after each run instead, the same thing Jupyter/
 * JupyterLite kernels do internally via their own display hook, so ordinary
 * `plt.plot(...); plt.show()` code a user pastes in just works without
 * needing to know about savefig().
 */

'use strict';

importScripts('/core/lib/pyodide/pyodide.js');

var pyodideReadyPromise = null;
var stdoutBuf = [];
var stderrBuf = [];

function ensurePyodide() {
  if (pyodideReadyPromise) return pyodideReadyPromise;
  pyodideReadyPromise = loadPyodide({ indexURL: '/core/lib/pyodide/' }).then(function (pyodide) {
    pyodide.setStdout({ batched: function (msg) { stdoutBuf.push(msg); } });
    pyodide.setStderr({ batched: function (msg) { stderrBuf.push(msg); } });
    return pyodide.loadPackage(['numpy', 'matplotlib']).then(function () {
      pyodide.runPython('import matplotlib\nmatplotlib.use("Agg")\n');
      return pyodide;
    });
  });
  return pyodideReadyPromise;
}

// Captures any matplotlib figures the cell's source left open, as base64
// PNGs, then closes them — only touches matplotlib if the cell itself
// already imported pyplot, so a plain stdlib cell never pays any
// matplotlib/Agg overhead.
function captureFigures(pyodide) {
  var code = [
    'import sys, io, base64',
    '__lk_images = []',
    "if 'matplotlib.pyplot' in sys.modules:",
    '    __lk_plt = sys.modules["matplotlib.pyplot"]',
    '    for __lk_num in __lk_plt.get_fignums():',
    '        __lk_fig = __lk_plt.figure(__lk_num)',
    '        __lk_buf = io.BytesIO()',
    '        __lk_fig.savefig(__lk_buf, format="png")',
    '        __lk_images.append(base64.b64encode(__lk_buf.getvalue()).decode("ascii"))',
    '    __lk_plt.close("all")',
    '__lk_images',
  ].join('\n');
  var proxy = pyodide.runPython(code);
  var images = proxy ? proxy.toJs() : [];
  if (proxy && typeof proxy.destroy === 'function') proxy.destroy();
  return images;
}

// runPythonAsync returns the last top-level expression's value (Pyodide's
// REPL-like eval semantics), or undefined/None otherwise. PyProxy results
// must be explicitly destroy()ed or they leak Python-side memory.
function reprResult(result) {
  if (result === undefined || result === null) return null;
  try {
    return (typeof result.toString === 'function') ? result.toString() : String(result);
  } finally {
    if (result && typeof result.destroy === 'function') result.destroy();
  }
}

self.onmessage = function (evt) {
  var data = evt.data;

  if (data.op === 'init') {
    ensurePyodide().then(function () {
      self.postMessage({ ok: true, op: 'init' });
    }).catch(function (e) {
      self.postMessage({ ok: false, op: 'init', error: String((e && e.message) || e) });
    });
    return;
  }

  if (data.op === 'run') {
    stdoutBuf = [];
    stderrBuf = [];
    ensurePyodide().then(function (pyodide) {
      return pyodide.runPythonAsync(data.source).then(function (result) {
        var text = reprResult(result);
        var images = captureFigures(pyodide);
        self.postMessage({
          id: data.id, ok: true,
          stdout: stdoutBuf.join('\n'), stderr: stderrBuf.join('\n'),
          result: text, images: images,
        });
      }, function (err) {
        var images = [];
        try { images = captureFigures(pyodide); } catch (e2) { /* best-effort */ }
        self.postMessage({
          id: data.id, ok: false,
          stdout: stdoutBuf.join('\n'), stderr: stderrBuf.join('\n'),
          error: String((err && err.message) || err), images: images,
        });
      });
    }).catch(function (e) {
      // ensurePyodide() itself failed (runtime/package load error) — the
      // cell's source never ran at all.
      self.postMessage({
        id: data.id, ok: false, stdout: '', stderr: '',
        error: String((e && e.message) || e), images: [],
      });
    });
  }
};
