
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var ca=Object.assign({},g),da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="object"==typeof window,ja="function"==typeof importScripts,ka="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",la,ma,na;
if(ka){r=ja?require("path").dirname(r)+"/":__dirname+"/";var fs,oa;"function"===typeof require&&(fs=require("fs"),oa=require("path"));la=(a,b)=>{a=oa.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};na=a=>{a=la(a,!0);a.buffer||(a=new Uint8Array(a));return a};ma=(a,b,c)=>{a=oa.normalize(a);fs.readFile(a,function(e,d){e?c(e):b(d.buffer)})};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);process.on("uncaughtException",
function(a){if(!(a instanceof pa))throw a;});process.on("unhandledRejection",function(a){throw a;});fa=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof pa||t("exiting due to exception: "+b);process.exit(a)};g.inspect=function(){return"[Emscripten Module object]"}}else if(ha||ja)ja?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):"",la=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},ja&&(na=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ma=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var qa=g.print||console.log.bind(console),t=g.printErr||console.warn.bind(console);Object.assign(g,ca);ca=null;
g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);var ra;g.wasmBinary&&(ra=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&w("no native wasm support detected");var sa,ta=!1,ua="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function va(a,b){for(var c=b+NaN,e=b;a[e]&&!(e>=c);)++e;if(16<e-b&&a.buffer&&ua)return ua.decode(a.subarray(b,e));for(c="";b<e;){var d=a[b++];if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var h=a[b++]&63;d=224==(d&240)?(d&15)<<12|f<<6|h:(d&7)<<18|f<<12|h<<6|a[b++]&63;65536>d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}return c}function x(a){return a?va(y,a):""}
function z(a,b,c,e){if(0<e){e=c+e-1;for(var d=0;d<a.length;++d){var f=a.charCodeAt(d);if(55296<=f&&57343>=f){var h=a.charCodeAt(++d);f=65536+((f&1023)<<10)|h&1023}if(127>=f){if(c>=e)break;b[c++]=f}else{if(2047>=f){if(c+1>=e)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=e)break;b[c++]=224|f>>12}else{if(c+3>=e)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}var E,y,wa,Q,V,xa,ya,za,Aa=[],Ba=[],Ca=[],Da=[];function Ea(){var a=g.preRun.shift();Aa.unshift(a)}
var Fa=0,Ga=null,Ha=null;function w(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";t(a);ta=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ia(){return Y.startsWith("data:application/octet-stream;base64,")}var Y;Y="run_boardie.wasm";if(!Ia()){var Ja=Y;Y=g.locateFile?g.locateFile(Ja,r):r+Ja}function Ka(){var a=Y;try{if(a==Y&&ra)return new Uint8Array(ra);if(na)return na(a);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}
function La(){if(!ra&&(ha||ja)){if("function"==typeof fetch&&!Y.startsWith("file://"))return fetch(Y,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Y+"'";return a.arrayBuffer()}).catch(function(){return Ka()});if(ma)return new Promise(function(a,b){ma(Y,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ka()})}
var Ma,Na,Qa={15432:()=>{window.J=[];window.addEventListener("message",function(a){if(a.data.constructor===Uint8Array)window.J.push(...a.data);else if(a.data.constructor===Array)switch(a.data[0]){case "putFile":window.localStorage[a.data[1]]=a.data[2];break;case "keyDown":window.keys.set(a.data[1],!0);break;case "keyUp":window.keys.set(a.data[1],!1);break;default:console.log("unrecognized message:",a.data[0])}},!1)},15954:()=>{var a=window.v?"session":"local";Object.keys(window.localStorage).forEach(function(b){window.parent.postMessage(["boardieGetFile",
b,window[a+"Storage"][b]],"*")})},16190:()=>window.J.splice(0,1)[0],16236:()=>{window.J||(window.J=[]);return 0<window.J.length},16329:(a,b,c)=>{for(var e=new Uint8Array(c-b),d=b;d<c;d++)e[d-b]=Oa(a+d);window.parent.postMessage(e,"*")},16483:()=>{window.keys=new Map;window.addEventListener("keydown",function(a){window.parent.postMessage(["boardieKeyDown",a.keyCode],"*");window.keys.set(a.keyCode,!0)},!1);window.addEventListener("keyup",function(a){window.parent.postMessage(["boardieKeyUp",a.keyCode],
"*");window.keys.set(a.keyCode,!1)},!1)},16849:()=>{window.F=new AudioContext;window.R=window.F.createGain();window.R.gain.value=.1;window.D=window.F.createOscillator();window.D.type="square";window.D.start();window.R.connect(window.F.destination)},17161:(a,b)=>{console.log(g.base64Encode(E.subarray(a,a+b),!0))},17239:()=>{var a=window.location.hash.indexOf("&files");0<a&&(window.v=!0,window.location.hash.substr(a+7).split(",").forEach(b=>{var c=b.indexOf(":"),e=decodeURIComponent(b.substring(0,c));
console.log("Loading",e);b=g.base64Decode(b.substring(c+1),!0);window.sessionStorage[e]=b}))},17735:a=>{if(window.location.hash.startsWith("#code=")){var b=window.location.hash.indexOf("&");b=window.location.hash.substring(6,-1<b?b:window.location.hash.length);console.log("Loading code from URL");if(b){b=g.base64Decode(b,!0);for(var c=0;c<b.length;c++){var e=a,d=b[c],f="i8";f.endsWith("*")&&(f="*");switch(f){case "i1":E[e>>0]=d;break;case "i8":E[e>>0]=d;break;case "i16":wa[e>>1]=d;break;case "i32":Q[e>>
2]=d;break;case "i64":Na=[d>>>0,(Ma=d,1<=+Math.abs(Ma)?0<Ma?(Math.min(+Math.floor(Ma/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Ma-+(~~Ma>>>0))/4294967296)>>>0:0)];Q[e>>2]=Na[0];Q[e+4>>2]=Na[1];break;case "float":xa[e>>2]=d;break;case "double":ya[e>>3]=d;break;case "*":V[e>>2]=d;break;default:w("invalid type for setValue: "+f)}a++}}}},18120:()=>window.keys.get(37)||window.keys.get(65)||window.keys.get(84),18198:()=>window.keys.get(39)||window.keys.get(66)||window.keys.get(84),18276:()=>{window.D.Z&&
(window.D.disconnect(),window.D.Z=!1,window.parent.postMessage(["boardieSoundStop"],"*"))},18436:a=>{window.D.frequency.value=a;window.D.Z=!0;window.parent.postMessage(["boardieSoundStart"],"*");window.D.connect(window.R)},18613:()=>{},18617:(a,b)=>{var c=0,e=new AudioBuffer({length:b,sampleRate:window.F.sampleRate}),d=e.getChannelData(0);for(let f=0;f<b;f++)d[f]=E[a+f]/255-.5,c++;window.H&&(window.H.stop(),window.H.disconnect());window.H=new AudioBufferSourceNode(window.F,{buffer:e});window.H.connect(window.F.destination);
window.H.start();return c},19162:a=>{var b=window.M!=a;window.M=a;return b},19255:(a,b)=>{window.m.fillStyle="#000";window.m.fillRect(0,0,a,b)},19325:(a,b)=>{window.O=document.createElement("canvas");window.O.width=a;window.O.height=b;window.m=window.O.getContext("2d",{alpha:!1});window.m.imageSmoothingEnabled=!1;(new FontFace("adafruit","url(adafruit_font.ttf)")).load().then(c=>{document.fonts.add(c)});window.o=function(c){return"rgb("+(c>>16&255)+","+(c>>8&255)+","+(c&255)+")"};window.u=function(c,
e){window.m.fillRect(c|0,e|0,1,1)};window.P=function(c,e,d,f,h){c|=0;e|=0;d|=0;f|=0;window.m.fillStyle=window.o(h);if(c===d)window.m.fillRect(c,Math.min(e,f),1,Math.abs(f-e)+1);else if(e===f)window.m.fillRect(Math.min(c,d),e,Math.abs(d-c)+1,1);else{h=Math.abs(d-c);for(var l=c<d?1:-1,k=-Math.abs(f-e),n=e<f?1:-1,p=h+k;;){window.u(c,e);if(c===d&&e===f)break;var q=2*p;q>=k&&(p+=k,c+=l);q<=h&&(p+=h,e+=n)}}};window.aa=function(c,e,d,f,h){c|=0;e|=0;d|=0;f|=0;0>=d||0>=f||(window.m.fillStyle=window.o(h),window.m.fillRect(c,
e,d,1),window.m.fillRect(c,e+f-1,d,1),window.m.fillRect(c,e,1,f),window.m.fillRect(c+d-1,e,1,f))};window.$=function(c,e,d,f){c|=0;e|=0;d|=0;if(!(0>d)){window.m.fillStyle=window.o(f);f=0;var h=d;for(d=3-2*d;h>=f;)window.u(c+f,e+h),window.u(c-f,e+h),window.u(c+f,e-h),window.u(c-f,e-h),window.u(c+h,e+f),window.u(c-h,e+f),window.u(c+h,e-f),window.u(c-h,e-f),0>d?d+=4*f+6:(d+=4*(f-h)+10,h--),f++}};window.ba=function(c,e,d,f,h,l){c|=0;e|=0;d|=0;f|=0;h|=0;if(!(0>=d||0>=f)){0>h&&(h=0);2*h>=f&&(h=(f>>1)-1);
2*h>=d&&(h=(d>>1)-1);0>h&&(h=0);window.m.fillStyle=window.o(l);window.m.fillRect(c+h,e,d-2*h,1);window.m.fillRect(c+h,e+f-1,d-2*h,1);window.m.fillRect(c,e+h,1,f-2*h);window.m.fillRect(c+d-1,e+h,1,f-2*h);l=c+h;c=c+d-h-1;d=e+h;e=e+f-h-1;f=0;var k=h;for(h=3-2*h;k>=f;)window.u(l-f,d-k),window.u(l-k,d-f),window.u(c+f,d-k),window.u(c+k,d-f),window.u(c+f,e+k),window.u(c+k,e+f),window.u(l-f,e+k),window.u(l-k,e+f),0>h?h+=4*f+6:(h+=4*(f-k)+10,k--),f++}}},22506:()=>{window.S||(window.S=document.querySelector("#screen").getContext("2d",
{alpha:!1}),window.S.imageSmoothingEnabled=!1);window.S.drawImage(window.O,0,0)},22726:(a,b,c,e)=>{window.M||(window.M=65280);window.m.fillStyle=0==e?"#000":window.o(window.M);window.m.fillRect(a,b,c,c)},22917:()=>{var a=window.document.querySelector("#screen");window.W=0;window.X=0;window.N=!1;window.T=0;a.addEventListener("pointermove",function(b){window.W=Math.floor(b.clientX-a.offsetLeft);window.X=Math.floor(b.clientY-a.offsetTop)},!1);a.addEventListener("pointerdown",function(){window.N=!0;window.T=
Date.now()},!1);a.addEventListener("pointerup",function(){window.N=!1;window.T=0},!1)},23508:(a,b,c)=>{window.m.fillStyle=window.o(c);window.m.fillRect(a,b,1,1)},23593:(a,b,c)=>{window.m.fillStyle=window.o(c);window.m.fillRect(a,b,1,1)},23678:(a,b,c)=>{window.m.fillStyle=window.o(c);window.m.fillRect(a,b,1,1)},23763:(a,b,c)=>{window.m.fillStyle=window.o(c);window.m.fillRect(a,b,1,1)},23848:(a,b,c)=>{window.m.fillStyle=window.o(c);window.m.fillRect(a,b,1,1)},23933:(a,b,c,e,d)=>{window.P(a,b,c,e,d)},
23973:(a,b,c,e,d,f)=>{f?(window.m.fillStyle=window.o(d),window.m.fillRect(a,b,c,e)):window.aa(a,b,c,e,d)},24117:(a,b,c,e,d,f,h)=>{h?window.m.fillStyle=window.o(f):window.m.strokeStyle=window.o(f);window.m.beginPath();window.m.moveTo(a+d,b);window.m.lineTo(a+c-d,b);window.m.arc(a+c-d,b+d,d,3*Math.PI/2,0,!1);window.m.lineTo(a+c,b+e-d);window.m.arc(a+c-d,b+e-d,d,0,Math.PI/2,!1);window.m.lineTo(a+d,b+e);window.m.arc(a+d,b+e-d,d,Math.PI/2,Math.PI,!1);window.m.lineTo(a,b+d);window.m.arc(a+d,b+d,d,Math.PI,
3*Math.PI/2,!1);h?window.m.fill():window.ba(a,b,c,e,d,f)},24827:(a,b,c,e,d)=>{d?(window.m.fillStyle=window.o(e),window.m.beginPath(),window.m.arc(a,b,c,0,2*Math.PI),window.m.fill()):window.$(a,b,c,e)},25066:(a,b,c,e,d,f,h,l)=>{l?window.m.fillStyle=window.o(h):window.m.strokeStyle=window.o(h);window.m.beginPath();window.m.moveTo(a,b);window.m.lineTo(c,e);window.m.lineTo(d,f);window.m.closePath();l?window.m.fill():(window.P(a,b,c,e,h),window.P(c,e,d,f,h),window.P(d,f,a,b,h))},25462:(a,b,c,e,d,f,h,l)=>
{a=x(a);var k=b-d,n=c-d;0<=h&&(b=6*d*a.length,window.m.fillStyle=window.o(h),window.m.fillRect(k+d,n+d,b,8*d));var p=3==d?10.5*d:11*d;window.m.fillStyle=window.o(e);window.m.textBaseline="top";l?(p=10*d,window.m.font=p+"px monospace",window.m.fillText(a,k+.9*d,n+2.45*d)):(window.m.font=p+"px adafruit",a.split("").forEach(q=>{window.m.fillText(q,k,n);k+=6*d;f&&k+6*d>=window.m.canvas.width&&(k=0-d,n+=3*p/4)}))},26308:(a,b,c,e,d,f,h,l)=>{var k=window.m.canvas.width/d;d=window.m.canvas.height/d;c/=b;
for(var n=0;n<c;n++)if(n+l<d&&0<=n+l)for(var p=0;p<b;p++)if(p+h<k&&0<=p+h){var q=y[a+n*b+p];q!==f&&(y[e+((l+n)*k+p+h)]=q)}},26766:(a,b)=>{window.U||(window.U=[]);window.U[b]=a},26841:(a,b,c,e,d,f)=>{b=b||1;var h=Math.ceil(window.m.canvas.width/b),l=Math.ceil(window.m.canvas.height/b);d=0<=d?d:h;f=0<=f?f:l;l=window.m.createImageData(d,f);var k=0,n=document.createElement("canvas");n.width=d;n.height=f;for(var p=e;p<e+f;p++)for(var q=c;q<c+d;q++){var G=window.U[y[a+p*h+q]];l.data[k]=G>>16;l.data[k+1]=
G>>8&255;l.data[k+2]=G&255;l.data[k+3]=255;k+=4}n.getContext("2d").putImageData(l,0,0);window.m.drawImage(n,c*b,e*b,d*b,f*b)},27851:()=>window.N,27879:()=>window.W,27905:()=>window.X,27931:()=>{if(window.N){var a=Date.now()-window.T;4095<a&&(a=4095)}else a=-1;return a},28121:a=>{window.B=new XMLHttpRequest;window.B.port=a;window.B.G=0},28235:a=>{window.B=new XMLHttpRequest;window.B.port=a;window.B.G=0},28349:()=>void 0!==window.B,28394:(a,b,c,e)=>{window.B=new XMLHttpRequest;var d=window.B;d.G=0;
d.open(x(a),window.location.protocol+"//"+x(b)+"/"+x(c));d.onreadystatechange=function(){4==d.readyState&&(d.V="HTTP/1.1 "+d.status+" "+d.statusText+"\r\n"+d.getAllResponseHeaders()+"\r\n\r\n"+d.responseText)};d.send(x(e))},28837:a=>{var b=window.B,c=0;b&&b.V&&(c=Math.min(b.V.length-b.G,799),z(b.V.substr(b.G,c),y,a,c+1),b.G+=c,0==c&&delete window.B);return c},29203:a=>window.keys.get(a),29235:a=>{a=x(a);"user-prefs"!==a&&(delete window[(window.v?"session":"local")+"Storage"][a],delete window.s[a],
window.parent.postMessage(["boardieDeleteFile",a],"*"))},29527:(a,b)=>{a=x(a);if("user-prefs"===a)return 0;var c=window.v?"session":"local";if(void 0===window[c+"Storage"][a])if(b)window[c+"Storage"][a]="";else return 0;window.L=5E4;window.s||(window.s={});if(!window.s[a]||b)window.s[a]=0;return 1},29994:a=>{a=x(a);return"user-prefs"===a?0:window.s[a]>=window[(window.v?"session":"local")+"Storage"][a].length},30223:(a,b)=>{a=x(a);if("user-prefs"!==a){var c=window[(window.v?"session":"local")+"Storage"][a];
if(window.s[a]<c.length){var e=c.indexOf("\n",window.s[a]);-1===e&&(e=c.length);z(c.substring(window.s[a],e),y,b,1024);window.s[a]=e+1}else z("",y,b,1024)}},30779:(a,b,c,e)=>{a=x(a);if("user-prefs"===a)return 0;var d=window[(window.v?"session":"local")+"Storage"][a];e=0<e?e:window.s[a];b=e+b>d.length?d.length:e+b;for(var f=e;f<b;f++)E[c]=d.charCodeAt(f),c++,(f-e)%window.L==window.L-1&&Pa(1);window.s[a]=b;return b-e},31363:(a,b,c)=>{a=x(a);if("user-prefs"===a)return 0;var e=window[(window.v?"session":
"local")+"Storage"][a],d=window.s[a];c=c+d>e.length?e.length:c+d;for(var f=d;f<c;f++)E[b]=e.charCodeAt(f),b++,(f-d)%window.L==window.L-1&&Pa(1);window.s[a]=c;return c-d},31931:a=>{a=x(a);return a in window.s?window.s[a]:0},32066:(a,b)=>{a=x(a);a in window.s&&(window.s[a]=b)},32228:(a,b)=>{a=x(a);if("user-prefs"!==a){b=x(b);var c=window.v?"session":"local";window[c+"Storage"][a]+=b+"\n";window.parent.postMessage(["boardieGetFile",a,window[c+"Storage"][a]],"*")}},32551:(a,b,c)=>{var e=window.v?"session":
"local";a=x(a);if("user-prefs"!==a){b=E.subarray(b,b+c);c=window[e+"Storage"][a];for(var d=0;d<b.length;d++)c+=String.fromCharCode(b[d]);window[e+"Storage"][a]=c;window.parent.postMessage(["boardieGetFile",a,window[e+"Storage"][a]],"*")}},33027:(a,b)=>{var c=window.v?"session":"local";a=x(a);"user-prefs"!==a&&(window[c+"Storage"][a]+=x(b),window.parent.postMessage(["boardieGetFile",a,window[c+"Storage"]],"*"))},33316:a=>{var b=window.v?"session":"local";a=x(a);return"user-prefs"===a?0:window[b+"Storage"][a].length},
33524:a=>{window.A=0;window.C=x(a);window.K=""},33613:a=>{var b=Object.keys(window[(window.v?"session":"local")+"Storage"]).filter(e=>"user-prefs"!==e&&!e.startsWith("-snap-"));void 0===window.A&&(window.A=0,window.C="",window.K="");for(z("",y,a,100);window.A<b.length;){var c=b[window.A];if(c.startsWith(window.C)&&c.length>window.C.length&&!c.includes("/",window.C.length+1)){z(c,y,a,100);window.A++;break}window.A++}},34274:a=>{var b=Object.keys(window[(window.v?"session":"local")+"Storage"]).filter(d=>
"user-prefs"!==d);void 0===window.A&&(window.A=0,window.C="",window.K="");for(z("",y,a,100);window.A<b.length;){var c=b[window.A];if(c.startsWith(window.C)){c=c.substring(window.C.length);c.startsWith("/")&&(c=c.substring(1));var e=c.indexOf("/");if(0<e&&!c.includes("/",e+1)&&(c=c.substring(0,e),c!=window.K&&c!=window.C)){z(c,y,a,100);window.K=c;break}}window.A++}},35108:a=>{"undefined"!==typeof navigator.requestMIDIAccess&&navigator.requestMIDIAccess().then(function(b){b=Array.from(b.outputs);var c=
a;0<b.length&&(c=Math.min(c,b.length-1),window.I=b[c][1],console.log("midi output:",window.I))})},35459:(a,b,c,e)=>{if("undefined"===typeof window.I)console.log("no midi output");else try{switch(a){case 1:window.I.send([b]);break;case 2:window.I.send([b,c]);break;case 3:window.I.send([b,c,e])}}catch(d){console.log(d)}}};function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ra(a){for(;0<a.length;)a.shift()(g)}
function Oa(a){var b="i8";b.endsWith("*")&&(b="*");switch(b){case "i1":return E[a>>0];case "i8":return E[a>>0];case "i16":return wa[a>>1];case "i32":return Q[a>>2];case "i64":return Q[a>>2];case "float":return xa[a>>2];case "double":return ya[a>>3];case "*":return V[a>>2];default:w("invalid type for getValue: "+b)}return null}var Sa=[];function Ta(a){a instanceof pa||"unwind"==a||fa(1,a)}function Ua(a){if(!ta)try{a()}catch(b){Ta(b)}}function Wa(a){setTimeout(function(){Ua(a)},1E4)}
function Xa(a){Ya||(Ya={});Ya[a]||(Ya[a]=1,ka&&(a="warning: "+a),t(a))}var Ya,Za=!1,Z=null,$a=0,ab=null,bb=0,cb=0,db=0,eb=0,fb=[],gb={},hb,ib,jb,kb=!1,lb=!1,mb=[];
function nb(){function a(){lb=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!ob){ob=!0;try{pb=!0}catch(c){pb=!1,t("warning: no blob constructor, cannot create blobs with mimetypes")}qb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:pb?null:t("warning: no BlobBuilder");rb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Y||"undefined"!=typeof rb||(t("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Y=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Y&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,e,d,f){var h=null;if(pb)try{h=new Blob([c],{type:sb(e)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:sb(e)}))}catch(n){Xa("Blob constructor present but fails: "+
n+"; falling back to blob builder")}h||(h=new qb,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=rb.createObjectURL(h),k=new Image;k.onload=()=>{k.complete||w("Image "+e+" could not be decoded");var n=document.createElement("canvas");n.width=k.width;n.height=k.height;n.getContext("2d").drawImage(k,0,0);rb.revokeObjectURL(l);d&&d(c)};k.onerror=()=>{qa("Image "+l+" could not be decoded");f&&f()};k.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.na&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,e,d,f){function h(){k||(k=!0,d&&d(c))}function l(){k||(k=!0,new Audio,f&&f())}var k=!1;if(pb){try{var n=new Blob([c],{type:sb(e)})}catch(q){return l()}n=rb.createObjectURL(n);var p=new Audio;p.addEventListener("canplaythrough",()=>h(p),!1);p.onerror=function(){if(!k){t("warning: browser could not fully decode audio "+e+", trying slower base64 approach");for(var q="",G=0,ia=0,Va=0;Va<c.length;Va++)for(G=G<<8|c[Va],ia+=8;6<=ia;){var Ib=G>>ia-6&63;ia-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[Ib]}2==
ia?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(G&3)<<4],q+="=="):4==ia&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(G&15)<<2],q+="=");p.src="data:audio/x-"+e.substr(-3)+";base64,"+q;h(p)}};p.src=n;Wa(function(){h(p)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!lb&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function tb(a,b,c,e){if(b&&g.m&&a==g.canvas)return g.m;var d;if(b){var f={antialias:!1,alpha:!1,la:1};if(e)for(var h in e)f[h]=e[h];if("undefined"!=typeof GL&&(d=GL.createContext(a,f)))var l=GL.getContext(d).ga}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof GLctx||w("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.m=l,b&&GL.ma(d),g.oa=b,mb.forEach(function(k){k()}),nb());return l}var ub=!1,vb=void 0,wb=void 0;
function xb(a,b){function c(){kb=!1;var f=e.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(e.exitFullscreen=yb,vb&&e.requestPointerLock(),kb=!0,wb?("undefined"!=typeof SDL&&(Q[SDL.screen>>2]=V[SDL.screen>>2]|8388608),zb(g.canvas),Ab()):zb(e)):(f.parentNode.insertBefore(e,f),f.parentNode.removeChild(f),wb?("undefined"!=typeof SDL&&(Q[SDL.screen>>2]=V[SDL.screen>>2]&
-8388609),zb(g.canvas),Ab()):zb(e));if(g.onFullScreen)g.onFullScreen(kb);if(g.onFullscreen)g.onFullscreen(kb)}vb=a;wb=b;"undefined"==typeof vb&&(vb=!0);"undefined"==typeof wb&&(wb=!1);var e=g.canvas;ub||(ub=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var d=document.createElement("div");e.parentNode.insertBefore(d,e);d.appendChild(e);
d.requestFullscreen=d.requestFullscreen||d.mozRequestFullScreen||d.msRequestFullscreen||(d.webkitRequestFullscreen?()=>d.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(d.webkitRequestFullScreen?()=>d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);d.requestFullscreen()}
function yb(){if(!kb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Bb=0;function Cb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Bb)Bb=b+1E3/60;else for(;b+2>=Bb;)Bb+=1E3/60;setTimeout(a,Math.max(Bb-b,0))}}
function sb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Db=[];function Ab(){var a=g.canvas;Db.forEach(function(b){b(a.width,a.height)})}
function zb(a,b,c){b&&c?(a.fa=b,a.da=c):(b=a.fa,c=a.da);var e=b,d=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(e/d<g.forcedAspectRatio?e=Math.round(d*g.forcedAspectRatio):d=Math.round(e/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/e,screen.height/d);e=Math.round(e*f);d=Math.round(d*
f)}wb?(a.width!=e&&(a.width=e),a.height!=d&&(a.height=d),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(e!=b||d!=c?(a.style.setProperty("width",e+"px","important"),a.style.setProperty("height",d+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var ob,pb,qb,rb;
function Eb(a,b){cb=a;db=b;if(ab)if(Za||(Za=!0),0==a)Z=function(){var e=Math.max(0,ib+b-Fb())|0;setTimeout(jb,e)};else if(1==a)Z=function(){Cb(jb)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",e=>{if("setimmediate"===e.data||"setimmediate"===e.data.target)e.stopPropagation(),c.shift()()},!0);setImmediate=function(e){c.push(e);ja?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(e),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Z=function(){setImmediate(jb)}}}var Fb;Fb=ka?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();function Gb(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ta=!0}fa(a,new pa(a))}
function Hb(a,b,c,e,d){!ab||w("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ab=a;bb=e;var f=$a;Za=!1;jb=function(){if(!ta)if(0<fb.length){var h=Date.now(),l=fb.shift();l.ka(l.ha);if(hb){var k=hb,n=0==k%1?k-1:Math.floor(k);hb=l.ia?n:(8*k+(n+.5))/9}qa('main loop blocker "'+l.name+'" took '+(Date.now()-h)+" ms");g.setStatus&&(h=g.statusMessage||"Please wait...",
l=hb,k=gb.ja,l?l<k?g.setStatus(h+" ("+(k-l)+"/"+k+")"):g.setStatus(h):g.setStatus(""));f<$a||setTimeout(jb,0)}else f<$a||(eb=eb+1|0,1==cb&&1<db&&0!=eb%db?Z():(0==cb&&(ib=Fb()),ta||g.preMainLoop&&!1===g.preMainLoop()||(Ua(a),g.postMainLoop&&g.postMainLoop()),f<$a||("object"==typeof SDL&&SDL.audio&&SDL.audio.ea&&SDL.audio.ea(),Z())))};d||(b&&0<b?Eb(0,1E3/b):Eb(1,1),Z());if(c)throw"unwind";}var Jb=[],Kb=[null,[],[]];g.requestFullscreen=function(a,b){xb(a,b)};g.requestAnimationFrame=function(a){Cb(a)};
g.setCanvasSize=function(a,b,c){zb(g.canvas,a,b);c||Ab()};g.pauseMainLoop=function(){Z=null;$a++};g.resumeMainLoop=function(){$a++;var a=cb,b=db,c=ab;ab=null;Hb(c,0,!1,bb,!0);Eb(a,b);Z()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,e){return tb(a,b,c,e)};
var Lb={a:function(a,b,c){Sa.length=0;var e;for(c>>=2;e=y[b++];)c+=105!=e&c,Sa.push(105==e?Q[c]:ya[c++>>1]),++c;return Qa[a].apply(null,Sa)},c:function(){return Date.now()},d:function(a,b,c){y.copyWithin(a,b,b+c)},e:function(a,b,c){var e=Jb[a];e||(a>=Jb.length&&(Jb.length=a+1),Jb[a]=e=za.get(a));Hb(e,b,c)},b:function(a,b,c,e){for(var d=0,f=0;f<c;f++){var h=V[b>>2],l=V[b+4>>2];b+=8;for(var k=0;k<l;k++){var n=y[h+k],p=Kb[a];0===n||10===n?((1===a?qa:t)(va(p,0)),p.length=0):p.push(n)}d+=l}V[e>>2]=d;return 0}};
(function(){function a(d){g.asm=d.exports;sa=g.asm.f;d=sa.buffer;g.HEAP8=E=new Int8Array(d);g.HEAP16=wa=new Int16Array(d);g.HEAP32=Q=new Int32Array(d);g.HEAPU8=y=new Uint8Array(d);g.HEAPU16=new Uint16Array(d);g.HEAPU32=V=new Uint32Array(d);g.HEAPF32=xa=new Float32Array(d);g.HEAPF64=ya=new Float64Array(d);za=g.asm.j;Ba.unshift(g.asm.g);Fa--;g.monitorRunDependencies&&g.monitorRunDependencies(Fa);0==Fa&&(null!==Ga&&(clearInterval(Ga),Ga=null),Ha&&(d=Ha,Ha=null,d()))}function b(d){a(d.instance)}function c(d){return La().then(function(f){return WebAssembly.instantiate(f,
e)}).then(function(f){return f}).then(d,function(f){t("failed to asynchronously prepare wasm: "+f);w(f)})}var e={a:Lb};Fa++;g.monitorRunDependencies&&g.monitorRunDependencies(Fa);if(g.instantiateWasm)try{return g.instantiateWasm(e,a)}catch(d){return t("Module.instantiateWasm callback failed with error: "+d),!1}(function(){return ra||"function"!=typeof WebAssembly.instantiateStreaming||Ia()||Y.startsWith("file://")||ka||"function"!=typeof fetch?c(b):fetch(Y,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,
e).then(b,function(f){t("wasm streaming compile failed: "+f);t("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.g).apply(null,arguments)};g._getScripts=function(){return(g._getScripts=g.asm.h).apply(null,arguments)};g._main=function(){return(g._main=g.asm.i).apply(null,arguments)};
var Pa=g._taskSleep=function(){return(Pa=g._taskSleep=g.asm.k).apply(null,arguments)},Mb=g.stackAlloc=function(){return(Mb=g.stackAlloc=g.asm.l).apply(null,arguments)},Nb;Ha=function Ob(){Nb||Pb();Nb||(Ha=Ob)};
function Qb(a){var b=g._main;a=a||[];a.unshift(ea);var c=a.length,e=Mb(4*(c+1)),d=e>>2;a.forEach(h=>{for(var l=Q,k=d++,n=0,p=0;p<h.length;++p){var q=h.charCodeAt(p);127>=q?n++:2047>=q?n+=2:55296<=q&&57343>=q?(n+=4,++p):n+=3}n+=1;p=Mb(n);z(h,E,p,n);l[k]=p});Q[d]=0;try{var f=b(c,e);Gb(f)}catch(h){Ta(h)}}
function Pb(){function a(){if(!Nb&&(Nb=!0,g.calledRun=!0,!ta)){Ra(Ba);Ra(Ca);if(g.onRuntimeInitialized)g.onRuntimeInitialized();Rb&&Qb(b);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Da.unshift(c)}Ra(Da)}}var b=b||da;if(!(0<Fa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ea();Ra(Aa);0<Fa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},
1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Rb=!0;g.noInitialRun&&(Rb=!1);Pb();
